### ISSUE TITLE
Documentation site seems to be down

### ISSUE THREAD

**Issue by CarlosGamez-Nova** [CodeDredd/pinia-orm#1044]
### Environment

Web browser: Microsoft Edge, Version 110.0.1587.63 (Official build) (64-bit)

### Reproduction

Attempt to load any page on the documentation site:
https://pinia-orm.codedredd.de/

### Describe the bug

404 error is returned

![image](https://user-images.githubusercontent.com/118949383/223969830-ce2925ac-0e66-4f9e-92ff-4f06c0c6a8e0.png)

**Comment by pkid169** [comment]
Just started looking into this package as a good candidate for a new project but literally couldn't find any documentation at this point :(

**Comment by CodeDredd** [comment]
i am on it

**Comment by CodeDredd** [comment]
closed by 761c4d0

**Comment by CodeDredd** [comment]
@pkid169 now you can look again 😉
