### ISSUE TITLE
Is destroy() an async method like hinted at in the docs?

### ISSUE THREAD

**Issue by benwick** [CodeDredd/pinia-orm#1049]
### Environment

https://pinia-orm.codedredd.de/guide/repository/deleting-data#deleting-data-1

In a code example you write `const user = await useRepo(User).destroy(2)` ...

### Reproduction

... but the method is not returning a promise. I have logged and I have looked in the code.

### Describe the bug

The code example might be wrong and misleading.

**Comment by CodeDredd** [comment]
Thanks for finding this. ❤️ Gonna change the docs.
