### ISSUE TITLE
Models from mapped repo instance are not reactive under certain conditions

### ISSUE THREAD

**Issue by benwick** [CodeDredd/pinia-orm#1058]
### Environment

Pinia ORM 1.5.1 in the playground

### Reproduction

https://pinia-orm-play.codedredd.de/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDscQLh2bxOcN3AlZcgKBAfPzXkK7cJmN9JOL-rwAJLqxAVBVJYK6eK6NJasOsCM1DizQtpSBIc29frW9EJh3YhahxDEcMGSPRujnABsk0antWwwZXsQ22ZrIDpyIPiyEFjgveCZF4hTiqIAAUzHRl8xug3UTaMa3houD+cRxTGgBOUN0ZDSS-7iD05B4CjlVjRbO+iy-qBmc5xXhAFB1HM2BQYYdAAF4cCuby8MKSailuEq7u+KgAPIAEoALIqDBHB4HBiH1sijZoraEwXmB76QWRwykeRQSIeclJUuST4vpO2x7H6bJnLgMF0FQrHyBQNxQJwhDMC8q6oeu6Gbr8WG8AAchA4lPEeiInk2dH2lirG6awEnnAALB6ZJSdgMnyvJAmAbOIELkxUHIfGEwbmK268HuS54URVGWjRZ4tmZ4HMXgXGTKS1JUM+r4bFOOwzgAuswRh0AYZpoKAACCYBgJMCzoKAqS6gYECpEQAA8KXEAAOuYKjwJIVAALytSAAB+NRRBQMwGJ10YUNZ-XtSoKhgHV3B9SAMxZuqo02Kk9TBLQkbcFmHAzR1ujLZuiA2Edc21Oqy14PIrCXSoAB8s0qM12QqFAdXIMgt1mBQkQUBg7RkmSYCbFl-UvR1c2NaQBjQ3NSNvUET14vUIEVlW5FlSCKjWHqTgkaw0j+GAVD1b4aAqMAwD+DcHDcXluTSDpBAqAcBw03T6Pcd9rOnBzByNSsdCI8jKNi+jJGC0YlZ4CRiCRAYYQSIg9V4wTiTPmTFOyNg8DU7T9PZiOzMvmzaSc9zJscCO-OW0LIuo69sNjAjr0iy10Ne9kT3PAFRB0LqdSk3TWJgAEeNc3LVYAOQLHH7XB3qHBhyb+GIHqjAqDjmd6s4MfyyocexVBSdZCHacZAzWMK3HkzDBCAH7BXKeh249WuLH9eN3rH6t+17WrS+tv54kPW59G4-INowDo+P1PNxwBz2JMC9Z6w2j2O1G96pMeQeNo-frwzyA79gw-yKPvMqJPEdR1Q2jb3fT1j5vkyREW1jaHHElxznSka9zbSG3hfEepN0bNHvrMSOqQn4vx6m-PE49tDLzXl-bMiBf7-0AcAugLMwFD2wDcaQAAVYOiB2CgMQdDYAr1RiFh1nYXSSAib6FxlkA2phzAWWkN-FQCxPqwPkJtV6edN6z3ngzReNdsyr1PtmVBa9D7YOABJamlIc4O1ONTOOpByYayoHHVe7UjgqGJKDMkF92qkIoQQahz9HBIPavQjqjD+HMP0AbNIHCwA2F8CoI0rgogqAKh4capQwjRgWiEQJ-C0jQEVK9CBts76d2kB+dGyAMBkkhh1dGkwdHs0nvowx8CVCNArnNCRBc5571YEvBmCiGnb0mOBAECQf4qIgEfYAlJqbo1MdgcxlIrHWPakBUQXdAJFRADVBaGsiABy3EQKcqdSY0CMBAeGYdXrZOphgV2NNjlzQ0SoLRpyZYED0QAKVYLobAABpABVzeldw4OmPA8B0iIj0VaWidB2kVGIB86YUBhggzJAAfmDvAHqxIADsryYZIxAZbO5DzsAoolmEiAFtdElxeYwY5RxjluNxecxoJLUVzRAnc3SiA1A4olu8zJnzvm-IMP8yKowgVgBBWCqAEKoWwu+T1ayxIWXI3RYSuOtzGXSqRsUxAei1CsEQEqg4r18kHCmcvWZ1VaCLIarwFZvwg5V3ToRVgNBxpF3jmXMiFd2rrI7lsnZBhSZfXxc4ZeKgpypFpM4G1dqTkdRfJTKAAb1TBDCKU7JLqI2ZNkNGvKngqCz0cBSpG1hpCcHMDm5G5zPHIHXhJbeNLcX0qYWWl8kgDa-zjvYKtrLQXsq+T8v5taD7SAbfAJtLarmypuT2+tvhB2tuRiq6mpbe39sHaS162qRksk5kAA

### Describe the bug

(1) We have a component with a mapped repo instance and a model queried with that instance in a computed variable (`user1` in the example).
(2) We have another component or part off the app with its own repo instance (first timeout in the example).
(3) We update data with this other instance.
(4) The data change is not reflected in `user1`.

For me, that use case is perfectly possible: I can change data from everywhere in the app and this data change should be reflected in every model. The same goes for the low level actions of the store, see second timeout.

I have found a workaround by using the `useRepo` method in the computed function (see `user2`) . But I want to be able to use the `mapRepos` helper.

### Additional context

I assume the problem comes from the `hydratedDataCache` of the repo - every instance creates a new cache. Shouldn't the cache be shared between repo instances of the same model?

**Comment by benwick** [comment]
@CodeDredd I just wanted to illustrate the problem. I use the options API in my real applications and have the same problems.

If you would ask me the shared cache should be managed / updated in your low level action methods of the store.

**Comment by CodeDredd** [comment]
@benwick hmmm... i don't know yet if this is a good idea. Because then i have to pass the hydrated model to the actions or using revive to update the hydrstion cache. But if i use revive, u would hydrate the same data twice if not the action is used directly which would impact on performance.

**Comment by CodeDredd** [comment]
Also there is the thing with the hooks. Right now there are not triggered on the low level actions. So this would be also needed to change.

**Comment by benwick** [comment]
@CodeDredd It was just an idea. I  have only a superficial view of your  code. I have an app, where the store is shared between websockets. This sharing is done with store actions, because these are "replayable".  But when a model is not updated after direct action calls that too can be problematic.

**Comment by CodeDredd** [comment]
@benwick dont get me wrong. I appreciate your input a lot 😉. I still don't know yet how to proceed with this. 
The shared cache is pretty clear. But the rest I have no idea yet. Going to think about it. 
Anyway thanks a lot for this.

**Comment by benwick** [comment]
> Also there is the thing with the hooks. Right now there are not triggered on the low level actions. So this would be also needed to change.

Mh, just my 2 cents: I don't see a reason why low level actions should trigger hooks. They should change state and this changed state should be picked up by all repos and models.

**Comment by CodeDredd** [comment]
> Mh, just my 2 cents: I don't see a reason why low level actions should trigger hooks. They should change state and this changed state should be picked up by all repos and models.

I think you are right....i am thinking right now that both is valid. Using repo actions or store action. Both triggering an update of cache & hooks. I am thinking just loud.
The one thing which is clear is, taht the first thing is always making a model out the new data so the magic of the model is used. I either create a new one or one from the cache. After that it lands to the store.

So the only solution i see is enhancing the actions...

**Comment by CodeDredd** [comment]
I've started #1066 to handle all what we discuessed here. @benwick If you got time you can look at the PR and tell me you thoughts.

**Comment by benwick** [comment]
I have looked over your changes - but I have to admit I am more puzzled than before. But that stems from my very superficial knowledge of the code and typescript in general. So this new function SharedHydratedDataCache will always return a new map? Surely not - but it is not obvious to me, how it will generate one map per model. Is this achieved through the typings?

One other (general) thing I don't understand: Why is the database always created anew when a repo is contructed? Shouldn't the database be a singleton once created?

**Comment by CodeDredd** [comment]
@benwick 
The shared hydration cache is now shared between repositories. Before it was more like one hydration cache each repo instance.

So far that i understood it, the database is always created to new to reflect the needed models for the query. Honostly i don't know what impact it has if the databases are registered completly for every repo only once. My guess is that it will screw up the queries with their relations if the database isn't regesitered always new.

The database isn't the same like in the backend.
