### ISSUE TITLE
Define a field as undefined not working as expected 

### ISSUE THREAD

**Issue by fermaud** [CodeDredd/pinia-orm#1064]
### Environment

Vue 2 + pinia + pinia ORM

### Reproduction

I'm trying to create a field that is `undefined` by default but it is set as `null`. 
`creationDate: this.attr(undefined),`

const newExp = new Experience();

Expected
`
{ creationDate: undefined } 
`

Result
`
{ creationDate: null } 
`

### Describe the bug

It should set a default value as `undefined` but it's `null`

**Comment by CodeDredd** [comment]
It's a architectual definition. All fields which are undefined are `null`. If you really need undefined then you can use a callback
````ts
creationDate: this.attr(() => undefined)
````

**Comment by fermaud** [comment]
Ok thank you for your response
