### ISSUE TITLE
Using hooks with Typescript

### ISSUE THREAD

**Issue by fermaud** [CodeDredd/pinia-orm#1067]
### Describe the feature

Hi ✋🏼 
I'm trying to use `saved(model, record)` hook ([docs](https://pinia-orm.codedredd.de/guide/model/lifecycle-hooks#mutation-lifecycle-hook)) with TS, of which type are the args `model`, `record` ? 
If I set `saved(model: Post)` I got the following error:
`Class static side 'typeof Post' incrorrectly extends base class static side 'typeof Post`

Thanks for your help

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by AntoninRousset** [comment]
I could type my before hooks like this
```ts
  static override saving(model: Post, record?: Partial<Post>): boolean | void {}
```
You could even remove the returned type.
