### ISSUE TITLE
[Peer-Bug] @nuxt/kit 3.3.0 breaks nuxt v2.16

### ISSUE THREAD

**Issue by mackwic** [CodeDredd/pinia-orm#1091]
### Environment

See here: https://github.com/nuxt/nuxt/issues/19717

### Reproduction

See here: https://github.com/nuxt/nuxt/issues/19717

### Describe the bug

Pinia-ORM depends on Nuxt Kit. Its last version 3.3.0 breaks Nuxt2 with Nuxt-bridge. Pinning to @nuxt/kit 3.2 solves the issue.

The root issue is here: https://github.com/nuxt/nuxt/issues/19717 

The work around I've used to fix this was to add this block in package.json:

```package.json
  "resolutions": {
    "**/@nuxt/kit": "^3.2.0 < 3.3.0"
  }

```

**Comment by CodeDredd** [comment]
Thanks for the notice @mackwic. I don't know if i have to do something. I think not because it's not related to pinia-orm/nuxt.
Feedback is welcome if there is something i can change for this.

**Comment by mackwic** [comment]
I agree, I think there's nothing to do on your part. This issue is only
here to point people to a workaround if they stumble upon the same bug

Le lun. 20 mars 2023 à 14:25, Gregor Becker ***@***.***> a
écrit :
