### ISSUE TITLE
Model to repo connection

### ISSUE THREAD

**Issue by DellanX** [CodeDredd/pinia-orm#1160]
### Describe the feature

Long story short, there is a need to be able to save from the model, such as ```model.save()``` or ```model.update()```

This plugin is amazing, and I was able to migrate all but one function call to the repo-based method calls easily.
However, for my last case, the repo is completely unknown by the caller. (Essentially, it's a view that can display many types loaded from an API).
If there was an accessor on the model or even a sibling function to useRepo to lookup the repo, that'd be ideal.
Something for the following type of scenario.

```typescript
// BaseModel inherits from the Pinia-Orm Model, but adds some base attributes such as name, created_at, updated_at
function renameClicked (model: BaseModel, name: string) { 
  model.alias = name;
  // Easy thing done, now to save it to the DB...
}
```

Some possible ideas
```ts
  // Does not compile, and is redundant
  useRepo(model).save(model);
  // Unideal, but easiest to implement in my mind, also redundant
  model.$repo().save(model)
  // Maybe less redundant?
  useRepoAction(model).save() // A wrapper that locates the correct repo and passes in 'model' to the repo action.
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
If you need the old vuex-orm way you can achieve it that way:

````ts
  class BaseModel extends Model {
    static save(records: Element[] | Element) {
      useRepo(this).save(records)
    }
  }

  class User extends BaseModel {
    static entity = 'users'

    @Attr() declare id: number
    @Attr() declare name: string
  }

````

````ts
// this works now
User.save({
      id: 1,
      name: 'Joda',
    })
````
