### ISSUE TITLE
Flush does not work

### ISSUE THREAD

**Issue by tintin10q** [CodeDredd/pinia-orm#12]
Flush does not work. It could be because this model has a list as a primary key?

```js
import { Model } from "pinia-orm";

export default class HumanSavedShow extends Model {
  static entity = "HumanSavedShow";
  static primaryKey = ["human_id", "show_id"];

  static fields() {
    return {
      human_id: this.uid(),
      show_id: this.uid(),
      added_at: this.number(0)
    };
  }
}
```

```vue
<template>
  <button @click="testFlush">Flush does not work</click>
</template>


<script setup lang="ts">
import { useRepo } from "pinia-orm";
import HumanSavedShow from "@/models/HumanSavedShow";

const SAVEDSHOWS = useRepo(Spotify_HumanSavedShow)

function testFlush() {
  console.log('There are ', SAVEDSHOWS.all().length, 'Shows');
  useRepo(Spotify_HumanSavedShow).flush();
  SAVEDSHOWS.flush();
  console.log('There are ', SAVEDSHOWS.all().length, 'Shows');
  SAVEDSHOWS.new()
  console.log('There are ', SAVEDSHOWS.all().length, 'Shows');
}
</script>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "App",
});
</script>
```

I would expect flush to delete all the records stored. https://next.vuex-orm.org/guide/repository/deleting-data.html#deleting-data

But it doesn't delete anything.

**Comment by tintin10q** [comment]
Right now it is impossible for me to delete these HumanSavedShow.

**Comment by CodeDredd** [comment]
@tintin10q thx for reporting. if i find time i am fixing it 😉.... the problem with flush is, that i dont use connection anymore the way it was used.

**Comment by tintin10q** [comment]
I have no idea what that means but thank you! Looking forward to the fix.

**Comment by tintin10q** [comment]
Could you give an update on this? It has been 2 months. When do you think you will have time to fix this?

**Comment by tintin10q** [comment]
Maybe sponsoring will help you find time easier 😉

**Comment by tintin10q** [comment]
@CodeDredd Maybe with sponsoring you will find it easier to find some time 😉

**Comment by CodeDredd** [comment]
@tintin10q Many thanks for the sponsering. Means a lot to me that you are my first sponsor! Will fix it soon now for you ❤️ 

Sorry for keeping you waiting that long. Having family & work sometimes leave me less time for open source work.

**Comment by CodeDredd** [comment]
It gets me thinking....maybe i should oftner wait until i fix something so i get more sponsoring 🤣 ... *just kidding....maybe*

**Comment by CodeDredd** [comment]
i am still on it....had just too much work past days. Just as information.
