### ISSUE TITLE
field as array

### ISSUE THREAD

**Issue by wormen** [CodeDredd/pinia-orm#1221]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `ssr`, `telemetry`, `runtimeConfig`, `app`, `typescript`, `modules`, `lodash`, `components`, `imports`, `alias`, `pwa`, `build`, `css`, `vite`
- Runtime Modules:  `@pinia/nuxt@0.4.9`, `@pinia-orm/nuxt@1.6.7`, `@vueuse/nuxt@10.1.0`, `nuxt-lodash@2.4.1`
- Build Modules:    `-`
------------------------------

### Reproduction

```
@Attr([]) declare groupId: string[];
```
after which i get an error

TypeError: Illegal constructor

### Describe the bug

what are the options to use decorators to declare that a field is an array? in the documentation, I did not find options for how this can be done, at most, there is an example for objects, but this is not what I need

**Comment by CodeDredd** [comment]
````ts 
import { ArrayCast } from 'pinia-orm/dist/casts'

@Attr([]) @Cast(() => ArrayCast) declare groupId: string[];
````

**Comment by wormen** [comment]
so I also tried, the error is the same as above

**Comment by CodeDredd** [comment]
I neede more information. I can't reproduce it. Can you please give me a full example or reproduction please 🙏 ?

**Comment by wormen** [comment]
here is a complete example of my model where i am getting the error

```
import { Model } from 'pinia-orm';
import { Cast, HasMany, Str } from 'pinia-orm/dist/decorators';
import { Uid } from 'pinia-orm/dist/uuid/v4';
import { SendingItemsStatus } from '~/common/enum/sending-items/sending-items.status';
import { MessageTypeEnum } from '~/common/enum/message/message-type.enum';
import SendingFile from './sending-file';
import { ArrayCast } from 'pinia-orm/dist/casts';

export default class SendingItem extends Model {
	static entity = 'sending_items';
	static primaryKey = '_id';

	@Uid() declare _id: string;

	@Str('') declare name: string;

	@Str(MessageTypeEnum.EMAIL) declare type: string; // email | sms | whatsapp

	@Str(SendingItemsStatus.NONE) declare status: string; // none | wait | planned | processing | done

	@Str('') declare subject: string; // тема письма

	@Str('') declare text: string;

	@Str('') declare senderId: string; // ID отправителя (email | sms | whatsapp)

	@Attr([]) @Cast(() => ArrayCast) declare groupId: string[]; // <--- error

	@HasMany(() => SendingFile, 'sendingId') declare files: SendingFile[];
}

```

**Comment by CodeDredd** [comment]
Ahhh now i see the mistake. You need to put the empty array as string.

```ts
import { Model } from 'pinia-orm';
import { Cast, HasMany, Str } from 'pinia-orm/dist/decorators';
import { Uid } from 'pinia-orm/dist/uuid/v4';
import { SendingItemsStatus } from '~/common/enum/sending-items/sending-items.status';
import { MessageTypeEnum } from '~/common/enum/message/message-type.enum';
import SendingFile from './sending-file';
import { ArrayCast } from 'pinia-orm/dist/casts';

export default class SendingItem extends Model {
	static entity = 'sending_items';
	static primaryKey = '_id';

	@Uid() declare _id: string;

	@Str('') declare name: string;

	@Str(MessageTypeEnum.EMAIL) declare type: string;

	@Str(SendingItemsStatus.NONE) declare status: string;

	@Str('') declare subject: string;

	@Str('') declare text: string;

	@Str('') declare senderId: string;

// right now you need to parse the default as string
	@Attr('[]') @Cast(() => ArrayCast) declare groupId: string[]; // <--- error

	@HasMany(() => SendingFile, 'sendingId') declare files: SendingFile[];
}

```

**Comment by wormen** [comment]
if I make an empty array as a string, this also does not change the situation, I also checked this earlier

additionally, here are screenshots from the IDE, it also highlights this error

![Снимок экрана от 2023-04-29 08-07-51](https://user-images.githubusercontent.com/8462339/235284648-06ee35d3-c967-4773-8538-7322f7441d01.png)

![Снимок экрана от 2023-04-29 08-08-19](https://user-images.githubusercontent.com/8462339/235284668-25c3d55f-fd7a-4533-94d2-cc46999bc3cc.png)

**Comment by CodeDredd** [comment]
You have forgotten to import `Attr` 😉 
`import { Cast, HasMany, Str } from 'pinia-orm/dist/decorators';`

**Comment by wormen** [comment]
thanks, that was my mistake
