### ISSUE TITLE
Missing id when creating new item

### ISSUE THREAD

**Issue by fermaud** [CodeDredd/pinia-orm#1223]
### Describe the feature

Hi ✋🏼 
When creating a new item in `pinia-orm` with `save()` there is no `id`or `$id` generated (like in vuex orm). Is this a planned feature?
Thanks

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
Hey there,

i dont know what you mean. Nromally you define a primary key in a field and if you define it as `uid` then there also an id generated.

**Comment by fermaud** [comment]
Ok thanks for your answer, we don't really need it but we just list the changes to migrate from vuexorm to piniaorm
