### ISSUE TITLE
incorrect saving of nested objects

### ISSUE THREAD

**Issue by wormen** [CodeDredd/pinia-orm#1270]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      ssr, telemetry, runtimeConfig, app, appConfig, typescript, modules, lodash, buildModules, components, imports, alias, pwa, build, css, vite
- Runtime Modules:  @pinia/nuxt@0.4.9, @pinia-orm/nuxt@1.6.7, @vueuse/nuxt@10.1.0, nuxt-lodash@2.4.1
- Build Modules:    @pinia/nuxt@0.4.9, @pinia-orm/nuxt@1.6.7, unplugin-icons/nuxt
------------------------------

### Describe the bug

when saving data, where objects are used as a value, saving occurs incorrectly

examples:

model
```
import { Model } from 'pinia-orm';
import { Attr, Bool, Str } from 'pinia-orm/dist/decorators';
import { Uid } from 'pinia-orm/dist/uuid/v4';

export default class Workspace extends Model {
	static entity = 'workspaces';
	static primaryKey = '_id';

	@Uid() declare _id: string;
	@Str('') declare name: string;
	@Str(null) declare icon: string;
	@Str('') declare description: string;
	@Attr({ active: false, date: '', time: '' }) declare earlyStart: Record<string, any>;
	@Attr({ date: '', time: '' }) declare start: Record<string, any>;
	@Attr({ date: '', time: '' }) declare end: Record<string, any>;
	@Attr({ active: false, date: '', time: '' }) declare reserveTime: Record<string, any>;
}
```

usage
```
const w = new Workspace({
  name: 'test',
  start: { date: 'test value', time: 'test value' }
});
workspaceRepo.save(w);
console.log(w);
```

displayed correctly in the console
![Снимок экрана от 2023-05-05 14-03-37](https://user-images.githubusercontent.com/8462339/236441615-f9677b1c-0a59-4ecd-91e6-b8acc896cb77.png)

but when saving test data there is no
![Снимок экрана от 2023-05-05 14-04-32](https://user-images.githubusercontent.com/8462339/236441788-ece9948c-b59e-4f7e-895b-9013d312f26e.png)

**Comment by mahmoudawadeen** [comment]
Playing around with the playground I also found that storing the example data the other way around doesn't work.

# Setup
Go to https://pinia-orm-play.codedredd.de/ and do the following changes:
## Data.js:
```
export default {
  todo: {
    title: "test",
    user: {
      id: 1,
      name: 'JohnK',
      avatarImgUrl: 'https://i.pravatar.cc/300?img=57',
      firstName: 'John',
      lastName: 'K',
    },
  }
}
```
## Todo.js
add user field
```
.....
      user: this.belongsTo(User, 'userId')
.....
```
## App.js

replace `userRepo.save(data.users)` with `todoRepo.save(data.todo)`

# Expected

1. Todo inserted to store
2. User inserted to store
3. `user.todos` populated when calling `userRepo.with('todos').get()`

# Reality
1. Todo inserted to store ✅ 
2. User inserted to store ❌ 
3. `user.todos` populated when calling `userRepo.with('todos').get()` ❌ 

# Notes
1. adding `useRepo.save(data.todo.user)` in `app.js` stores the user, but still doesn't achieve .3
2. doing the previous step and adding foreign key in `todo` `userId: 1`, achieves .3

**Comment by CodeDredd** [comment]
Hello,
your model is wron. You need to use the `ArrayCast` for the object fields.

````ts
import { Model } from 'pinia-orm';
import { Attr, Bool, Str, Cast } from 'pinia-orm/dist/decorators';
import { ArrayCast } from 'pinia-orm/dist/casts';
import { Uid } from 'pinia-orm/dist/uuid/v4';

export default class Workspace extends Model {
	static entity = 'workspaces';
	static primaryKey = '_id';

	@Uid() declare _id: string;
	@Str('') declare name: string;
	@Str(null) declare icon: string;
	@Str('') declare description: string;
	@Cast(() => ArrayCast) @Attr({ active: false, date: '', time: '' }) declare earlyStart: Record<string, any>;
	@Cast(() => ArrayCast) @Attr({ date: '', time: '' }) declare start: Record<string, any>;
	@Cast(() => ArrayCast) @Attr({ date: '', time: '' }) declare end: Record<string, any>;
	@Cast(() => ArrayCast) @Attr({ active: false, date: '', time: '' }) declare reserveTime: Record<string, any>;
}
````

**Comment by joel-schou-maersk** [comment]
@CodeDredd Please forgive the naive question, but _why_? The name `ArrayCast` implies, well, an array. I cannot find anything in the docs explaining this need.

**Comment by CodeDredd** [comment]
It's done that way because an object can be more than just a simple object with attributes. there is also the date object and others. I guess that's the reason why....but maybe i find an "autodetect" for this 😉
