### ISSUE TITLE
Allow questions in the GitHub issue tracker

### ISSUE THREAD

**Issue by erikpols** [CodeDredd/pinia-orm#138]
### What problem is this solving

There is no place to ask questions about Pinia ORM. If its supposed to replace Vuex-orm, there should be.

### Proposed solution

Allow questions instead of a redirect to the Pinia repository

### Describe alternatives you've considered

Use reddit

**Comment by CodeDredd** [comment]
Actially there is a place to ask questions -》 
https://github.com/CodeDredd/pinia-orm/discussions
And I will soon link to discord vuejs - pinia for another place. I think that should be sufficient. 
On reddit I also look from time to time. But I don't think it should be the main place for discussions.

**Comment by erikpols** [comment]
ty I missed that.
