### ISSUE TITLE
.whereId throws exeption that repo.whereId is not a function

### ISSUE THREAD

**Issue by pwfraley** [CodeDredd/pinia-orm#1416]
### Environment

Quasar

### Reproduction

Create a Model and a repo and then us the repo in a component.

userRepo.query().whereId(ID) //Works

userRepo.whereId(ID) // Throws exception

### Describe the bug

No PR

**Comment by CodeDredd** [comment]
well i always wondered  if some1 finds this worth a ticket ^^....
I really think about having all in `query()` because it adds so much duplicate code on repository....
but yes i am going to add this one too 😉

**Comment by tintin10q** [comment]
If it would really increase the bundle size then don't do it. Also doesn't `.find` already do this?

**Comment by CodeDredd** [comment]
@tintin10q yes find does this. I need to find a better sollution for all `query` functions which are duplicated in repository.
