### ISSUE TITLE
chunk-NRQ5LZ2P.js:97 [Vue warn]: onUnmounted is called when there is no active component instance to be associated with

### ISSUE THREAD

**Issue by Pok09** [CodeDredd/pinia-orm#1432]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.5
- Builder:          vite
- User Config:      devtools, app, css, modules, build, runtimeConfig, quasar, image, anime, dayjs
- Runtime Modules:  nuxt-quasar-ui@2.0.2, @nuxt/image@1.0.0-rc.1, dayjs-nuxt@1.1.2, @vueuse/motion/nuxt@2.0.0, @hypernym/nuxt-anime@2.1.0, nuxt-lodash@2.5.0, @pinia/nuxt@0.4.11, @pinia-orm/nuxt@1.6.7, @pinia-plugin-persistedstate/nuxt@1.1.1, nuxt-vue3-google-signin@0.0.8, @nuxtjs/eslint-module@4.1.0
- Build Modules:    -

### Reproduction

```
<script lang="ts" setup>
import Collection from '~/store/models/collection'

const collections = computed(() => {
  return useRepo(Collection)
    .with('courses', (query) => {
      query.orderBy('updatedAt', 'desc')
    })
    .orderBy('updatedAt', 'desc')
    .get()
})
</scrip>

<template>
    <q-page>
          <section>
                <div
                      v-for="(collection, i) in collections"
                      :key="i"
                      class="col-xs-12 col-sm-6 col-md-3 q-pa-sm"
                    >
                    ...
                  </div>
          <section>
    </q-page>
</template>
```
![image](https://github.com/CodeDredd/pinia-orm/assets/24459601/4521a0a8-a2d2-4cff-b231-f21c36b1a8b7)

### Describe the bug

Everything seems to be working fine,
but when I use a variable initialized with pinia-orm in the template, a warning message is displayed on the console

### Logs

```shell
[Vue warn]: onUnmounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
```

Reproduction
[https://stackblitz.com/edit/nuxt-starter-ydvf86?embed=1&file=app.vue](https://stackblitz.com/edit/nuxt-starter-ydvf86?embed=1&file=app.vue)

**Comment by CodeDredd** [comment]
Thats difficult. Can you please provide a working reproduction? 🙏 
I think it has to do with quasar because they use a lot of these hooks.

**Comment by Pok09** [comment]
@CodeDredd 
I saw where the bug came from, while I was doing the [reproduction](https://stackblitz.com/edit/nuxt-starter-ydvf86)

```
const collections = computed(() => {
  return useRepo(Collection)
    .with('courses') <= here
    .get()
})
```
I called a relationship without initializing the repo course
