### ISSUE TITLE
Repository piniaStore() returns different piniaStoreInstance, when using a derivedModel

### ISSUE THREAD

**Issue by adm-bome** [CodeDredd/pinia-orm#1437]
### Discussed in https://github.com/CodeDredd/pinia-orm/discussions/1434

<div type='discussions-op-text'>

<sup>Originally posted by **adm-bome** July  3, 2023</sup>
Why does the Repository uses the `$entity()` as a name for the Pinia Store, while the Query uses the `$baseEntity()`. Is this by design or by mistake?

https://github.com/CodeDredd/pinia-orm/blob/43126f6b15a19dca099a05de7d9f78a13421c21b/packages/pinia-orm/src/repository/Repository.ts#L117-L119

https://github.com/CodeDredd/pinia-orm/blob/43126f6b15a19dca099a05de7d9f78a13421c21b/packages/pinia-orm/src/query/Query.ts#L163-L172

When creating a Model extended from an other Model we use baseEntity in the exteded Model.

```js
// Base entity.
class Person extends Model {
  static entity = 'person'
  static types () {
    return {
      PERSON: Person,
      ADULT: Adult
    }
  }
  static fields () {
    return {
      id: this.attr(null),
      name: this.attr('')
    }
  }
}
```
```js
// Derived entity.
class Adult extends Person { 
  static entity = 'adult'
  static baseEntity = 'person'
  static fields () {
    return {
      ...super.fields(),
      job: this.attr('')
    }
  } 

```

When we use the following code, a store is created with the name `adult`

```js
const repo = useRepo(Adult)
const store = repo.piniaStore() // Wrong StoreInstance
```

But when we use the following code a store is created and data is saved into the piniaStoreInstance with the name `person`

```js
const repo = useRepo(Adult)
repo.save([{ id: 1 }])
```
</div>

**Comment by CodeDredd** [comment]
You are right about the `piniaStore` instance. That's a bug. 👋 
The saving you mention behaves correct since you use typed STI everything is stored in the `baseEntity`.

**Comment by adm-bome** [comment]
@CodeDredd 
Did you see my comment in this discussion, what do you think? 

It solves:
- the $entity() / $baseEntity() calls by always using $baseEntity() 

It add abbility:
- to use or rename the storeName different than the actial model name
- to use a prefix to prevent duplicate stores.
- to override the method piniaStoreName(), when a developer needs a different outcome, without interfering with the outcome of $entity() and $baseEntity() methods.
