### ISSUE TITLE
Many-to-many orderBy pivot

### ISSUE THREAD

**Issue by bradley-varol** [CodeDredd/pinia-orm#1461]
### Describe the feature

I would like to be able to order a many-to-many relationship by a pivot table field:

```
collection() {
    return useRepo(Collection)
        .with('user')
        .with('tracks', q => q.with('user').orderBy('pivot.created_at', 'desc'))
        .find(this.collectionId)
},
```

I would expect a collection with a tracks array sorted by the `created_at` field on the pivot model. Is this possible (with Nuxt 2)?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
I think it should be possible if you use the `sortBy` helper function https://pinia-orm.codedredd.de/api/composables/helpers/use-sort-by

**Comment by tintin10q** [comment]
Can you give an example of that?

**Comment by CodeDredd** [comment]
I just changed the code so that the example works:
````ts
const users = userRepo.with('roles').orderBy((user) => {
      user.roles = useSortBy(user.roles, [['pivot.level', 'asc']])
    }).get()
````
