### ISSUE TITLE
Maybe document simple workaround for useDefineForClassFields: true 

### ISSUE THREAD

**Issue by 2-5** [CodeDredd/pinia-orm#148]
As documented, `pinia-orm` (and `vuex-orm`) is incompatible with the TypeScript setting `useDefineForClassFields: true`

But the world is moving towards this setting, and the number of other packages which require it keeps growing.

While investigating this issue, I found a nice workaround which works in all 4 combinations - `pinia-orm` x `vuex-orm` x `useDefineForClassFields: true` x `useDefineForClassFields: false`

One just needs to change the model field declarations from `id!: string` to `declare id: string`, like below. This prevents the creation of new style class fields which hide the old style properties, while keeping the typing information:

```typescript
export default class User extends Model {

  // ...

  declare id: string
  declare name: string
  declare email: string
}
```

`declare` was specifically added to TypeScript to solve `useDefineForClassFields: true` related issues:
https://www.typescriptlang.org/docs/handbook/2/classes.html#type-only-field-declarations

Maybe it's a good idea to document this possible workaround or maybe even recommended it as the way to declare new models. I'm not sure if it has other implications or failure modes, it works for my case, but I'm not using all `pinia-orm` features.

**Comment by CodeDredd** [comment]
@2-5 Thanks for the great post!
Your absolutly right....It's time to move on and i am going to test it and think about it.
I already used `declare` in one unit test to overwrite an existing property in a STI example:

````ts
    class Dog extends Animal {
      static entity = 'dogs'

      static baseEntity = 'animals'

      static fields() {
        return {
          ...super.schemas[super.entity],
        }
      }

      @Attr('dog') declare type
      @Attr('terrier') race!: string
    }
````
