### ISSUE TITLE
strange results of model methods

### ISSUE THREAD

**Issue by ahoyahoy** [CodeDredd/pinia-orm#1569]
### Environment

playground

### Reproduction

[playground demo](https://pinia-orm-play.codedredd.de/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDscQLh2bxOcN3AlZcgKBAfPzXkK7cJmN9JOL-rwAJLqxAVBVJYK6eK6NJasOsCM1DizQtpSBIc29frW9EJh3YhahxDEcMGSPRujnABsk0antWwwZXsQ22ZrIDpyIPiyEFjgveCZF4hTiqIAAUzHRl8xug3UTaMa3houD+cRxTGgBOUN0ZDSS-7iD05B4CjlVjRbO+iy-qBmc5xXhAFB1HM2BQYYdAAF4cCuby8MKSailuEq7u+KgAPIAEoALIqDBHB4HBiH1sijZoraEwXmB76QWRwykeRQSIeclKTEOZJPi+k7bHsfpsmcuAwXQVCsfIFA3FAnCEMwLyrqh67oZuvxYbwAByEASU8R6IieTZ0faWKsXprCSecAAsHp8TB2CyfKCmCYBs4gQuTFQch8YTBuYrbrwe5LnhRFUZaNFni25ngcxeBcTxw78a+GxTjsM4ALrMEYdAGGaaCgAAgmAYCTAs6CgKkuoGBAqREAAPFQ2QADrmCoYC1dwAC8LUgDMWbqhQ3BZvUwS0JGI2pBwfVtSoKi6L1LASIgNize1tTqkteDyKw63zQAfHNKhNdkR3tfNDUvpW2B+FAtXIMgS2lPAFCPBQA5kmSfUHfhiDwKQtX1FQdUQA1dzSDd8DnfNl1gNYB3AMAeK5AcBzg-DiAw7DV2Q-Id0PU9fUvW9IIfV9P24ZI8BmPkIPSGDENQ9jcMI0jKPIFTdA07gBhoxjCPHZd134yo90QI9z2ve9n3fSAB1qHQHChG4oPgyLt0sydgNa5dQQqMQFC1BwS0o6Y5gc31KhoDAiAhKbNwcJMIE-ezjvO6caMqBQKhuwBAAkz6K8rITaPY-MrHQWvgzrx3g81xDnfHZ3PIFRB0LqdTSL7KjWEYjBi7MYABCCKgHBWVYAOQLJXbUZ3qys53if16mXFd4ColdxVBtdZJnjcQtm7ed5MwyD07+y9-XWeqwzw+V6P9MfpPbVtQNL7+I7LeJN1m+INv2jj-Yq+2PIG8owCnjytnu959o2CAwYx-YG1KPb5MeQeNoS+TBzz9r2fbOHMVC7yxMXVIVBtBhxAQdPeHB36GAMGHf+p9sDn0dpzamtMDAgMLrqEukDoHdVgRzcqhhyA7GjNoUgMD-CTH9kgaQXMeaGGQSg9e2drA7Q8AAFVYFQHeOhJKOGIb7Y6CQBHvzEHjUOwi2oHCAqIUGgFCogGqp1OqZxU5biIFOBu2caBGAgIDbOwBjoczQCoDAQsxEXVhpJSxlJGA2PmiBSxlcABSrBdDYAANKV2cXYo4NizF2Pmg4lQjRAmw1hm4zuHi9KIDUAEmxwS7GhJieEqglj2jRMyXEyufC8AAAkUlBOOpleRijx4qKqrQDR9VeDaN+OnfupiVCEX4Z4NuRhKwdy7t5Mivc2p6JnoY4xBhs7i0ehkR2KgpypFpM4TpNAcEZJUC+OqdAoDzPVMEMIu9K4c2Ge1TZsgdm5U8FQZA0D1nzWsNITg5g7n2OyYWZ8v9JJhzyTEuJ0hdAfOur4bQldK72B+WXY6BwqlowOEAA)

### Describe the bug

I noticed that my models have wrong data in the template when using $methods.
In the demo you can see the correct data at the top, 
below that wrong data using the $getOriginal() method,
and the $isDirty() mark below, which is actually related to the fact that all the models in the upper section were overwritten from one (last) model to correct data and became dirty.

**Comment by CodeDredd** [comment]
Hey @ahoyahoy ,
first many thanks for your support ❤️ . That means a lot to me 😄 . Can't say enough thank you!
So at least what i can do is looking at your bug. Thanks for finding it.
Going to look into it.
