### ISSUE TITLE
Pass pinia options in model

### ISSUE THREAD

**Issue by JochemVanIterson** [CodeDredd/pinia-orm#16]
Hi!

I'm currently working on a project in which I have to migrate from Vue2 with Vuex-ORM into Vue3 with Pinia-ORM. One of the requirements of the project is to persist the store during page reloads (which I try to accomplish with the [pinia-plugin-persistedstate](https://github.com/prazdevs/pinia-plugin-persistedstate) plugin). To configure this plugin I have to add an option to my store description.

The issue I'm facing is that I can't figure out how to access this store description inside of a Model. I can imagine that other plugins will work the same way (options in the store description), so it might be an interesting addition to the package!

My proposed solution is to add a static field to the Model in which you could add options that are inserted (with a spread operator) into the store description. Maybe something like `static piniaOptions = {}`?

**Comment by CodeDredd** [comment]
But i think the persist thing will be your least problem if you want to move from vuex-orm to pinia-orm, because this is based on vuex-orm-next. So maybe some relation functions which are maybe used in your project arent yet there.

**Comment by JochemVanIterson** [comment]
> @JochemVanIterson In fact where is already a way implemented:
> 
> the second argument of `useRepo`, takes a pinia store definition.
> 
> ```ts
> export function useRepo(
>   modelOrRepository: any,
>   storeGenerator?: (id: string) => StoreDefinition,
>   connection?: string
> )
> ```
> 
> but i defently will be moving pinia store defenitions to the model.

Cool! Thanks a lot!

**Comment by JochemVanIterson** [comment]
> But i think the persist thing will be your least problem if you want to move from vuex-orm to pinia-orm, because this is based on vuex-orm-next. So maybe some relation functions which are maybe used in your project arent yet there.

Yes, I'm also using the [vuex-orm-axios](https://vuex-orm.github.io/plugin-axios/) and [graphql](https://vuex-orm.github.io/plugin-graphql/) plugins, but these are definitely broken on the new version (haven't tested them though). It's going to be a long transition I imagine!
