### ISSUE TITLE
Single Table Inheritance with types never returns from inherited tables but only from the base entity

### ISSUE THREAD

**Issue by tintin10q** [CodeDredd/pinia-orm#1631]
### Reproduction

```vue
<script setup lang="ts">
import { computed } from "vue";

import { Model, useRepo } from "pinia-orm";

// Base entity.
class Person extends Model {
  static entity = "person";
  static typeKey = "person_type"
  static types() {
    return {
      PERSON: Person,
      ADULT: Adult,
    };
  }
  static fields() {
    return {
      id: this.attr(null),
      name: this.attr(""),
      person_type: this.string("No type given?"),
    };
  }
}
// Derived entity.
class Adult extends Person {
  static entity = "adult";
  static baseEntity = "person";
  static fields() {
    return {
      ...super.fields(),
      job: this.attr(""),
    };
  }
}
const adult = useRepo(Adult);
const person = useRepo(Person);

const all_persons = computed(() => person.all());
const all_adults = computed(() => adult.all());

function clear() {
  adult.flush();
  person.flush();
}
</script>

<template>
  <button @click="clear">Clear</button>
  <br>
  <br>
  <button
    @click="
      person.insert([
        { person_type: 'PERSON', id: 1, name: 'John Doe' },
        { person_type: 'ADULT', id: 2, name: 'Jane Doe', job: 'Software Engineer' },
      ])
    "
  >
    Insert Person and adult through person
  </button>
  <br>
  <br>
  <button
    @click="
      adult.insert([
        // { person_type: 'PERSON', id: 1, name: 'John Doe' },
        { person_type: 'ADULT', id: 2, name: 'Jane Doe', job: 'Software Engineer' },
      ])
    "
  >
    Insert adult
  </button>
  <h2>Adults</h2>
  <div v-for="a in all_adults">- {{ a }} </div>

  <h2>Persons</h2>
  <div v-for="p in all_persons">- {{ p }} </div>
</template>
```

### Describe the bug

1. Click the `Insert Person and adult through person` button
2. Observe that only the people section gets populated but not the adults 

![image](https://github.com/CodeDredd/pinia-orm/assets/24190849/f3f1270a-6b50-4b89-a5b3-647d3079f762)

I would expect that the adults list would also be populated.

Even when you try to insert adults directly through the adults model it still does not show up on the page.  

### Additional context

The person table does work as expected which is really great! It returns all the persons including the adults. The adults have the specific adult fields and the persons do not. So the bug is that the other models do not seem to be populated. 

This also effects other models that have relationships with the sub models of person. So like if I would have a drink model which has a one to many relationship with adults called liked_by then this never gets populated. I left that out for the minimum example.

**Comment by tintin10q** [comment]
Also I hope that some coffee and cake will motivate you to fix these single table inheritance bugs because it really is exactly what I need. For some reason I read over the whole section in the docs up till now. Also can't wait for v1.7.0 ❤️

**Comment by tintin10q** [comment]
Here is just something extra I noticed when I remove baseEntity. I don't know how important this is.

When you remove the static baseEntity field from adult then adult gets disconnected from person. In this scenario you can still insert adults through person which will show up in person and not in adults. But if you insert adults through adults they won't show up in person but will show up in adults. See the gif if my prose does not make sense. 

![image](https://github.com/CodeDredd/pinia-orm/assets/24190849/de07be29-d66d-4c61-908c-08fb638bb482)

**Comment by tintin10q** [comment]
Alright what I was missing is that you also have to specify typeKey on the models that inherit from the base entity. This was not clear in the docs. This should probably be added to [Inheritance Conventions](https://pinia-orm.codedredd.de/guide/model/single-table-inheritance#inheritance-conventions). Thanks for pointing it out here https://github.com/CodeDredd/pinia-orm/issues/1629#issuecomment-1712733433

**Comment by tintin10q** [comment]
Maybe a warning when you do not expose the typedKey field on the inheriting entity would be a good idea.

**Comment by CodeDredd** [comment]
@tintin10q Many thanks for your support btw. Yes the extra coffee helps me being motivated 👍 ❤️ .
I will add as propossed some warnings and edit the docs.
But it is good to know that besides that STI works. In vuex-orm it never worked bugfree.
And here it's just missing good documentation .
