### ISSUE TITLE
Hot Module reloading in vite

### ISSUE THREAD

**Issue by tintin10q** [CodeDredd/pinia-orm#1645]
### Describe the feature

With hot module reloading you don't have to do a full page refresh to view the changes you made in the code. This is quite nice and makes iterating much faster. Pinia supports hot module reloading with code like this:

```js
import { acceptHMRUpdate } from "pinia";


if (import.meta?.hot) {
  import.meta.hot.accept(acceptHMRUpdate(useSomeStore, import.meta.hot));
}
```

Also see: https://vitejs.dev/guide/api-hmr.html

Is something like this also possible for pinia orm? At the moment every time I change anything about a pinia-orm model it reloads the whole page. Is a hmr like with pinia possible? 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
Good question....it should be possible. But i think this one of the low prio features ^^.

**Comment by tintin10q** [comment]
It sounds like it would be quite complicated. Then indeed low priority. I had hoped it might be simple :)

**Comment by tintin10q** [comment]
Woah thanks for doing this anyways!
