### ISSUE TITLE
original data in hooks

### ISSUE THREAD

**Issue by ahoyahoy** [CodeDredd/pinia-orm#1707]
### Environment

latest

### Reproduction

[playground](https://pinia-orm-play.codedredd.de/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDscQLh2bxOcN3AlZcgKBAfPzXkK7cJmN9JOL-rwAJLqxAVBVJYK6eK6NJasOsCM1DizQtpSBIc29frW9EJh3YhahxDEcMGSPRujnABsk0antWwwZXsQ22ZrIDpyIPiyEFjgveCZF4hTiqIAAUzHRl8xug3UTaMa3houD+cR5TJgPQ3RkNJL-uIPTkHgKOVWNFs76WX9QMznOK8IAoOo5mwSDDDoAAvDgVzeXhhSTUUtwlXc3xUAB5AAlABZFRoI4PBYIQ+tkUbNFbQmC9QLfCDSOGEiyKCBDzjvAB2clH2fSdtj2P02TOXBoLoKgWPkCgbigThCGYF5VxQ9c0M3X5MN4AA5CBxKeI9ERPJtaPtLEWN01gJPOAAWD0ySk7AZPleSBIA2dgIXRjIKQ+MJg3MVt14Pcl1wwjKMtaizxbMywKYvBOMmHj7KoJ8Xw2KcdhnABdZgjDoAwzTQUAAEEwDASYFnQUBUl1AwIFSIgAB4UuIAA+AAdbAbjSGYutlRBOsax82ueAKiDoXU6mkFRgBUawjEYFQsTAAIQRUA4KyrAByBYts6ia9Q4abZrxPDED1dbNrwFQttiyC9qySajoyG56iMStrq2yZhghf99geg6prcerXHe7bvqoEHfQezreuffxXrOi6AF4EcQJHWG0X6OHsTrOrxDgMcmPIPG0SHpHfAnkFx7BYfkeGqZUVHltWqhtG0RxkdatHCfO1hJkifNtC2hIqH1Lb7EmJBpA5mm6a66bSCZnnkAqwxyAwMksvxyZgOVraAA0AE0Ydsen+smLx4GFuxdKQUFgLQLbFtIXXThpuGLat4W6joeAzHyR3nf8SYABJpZwyR-dwAwObdggaYJomScQbRSBpwC+FeqVKioCryCqkAarAOqGt4ZrsiWurkGQZH2pASIKCMUgIhUMjNgoRvPxUUp4E73RgjSSt+BoKgKAMPxSjqGh6injgZ4oeAKhCChGjJMkVAJMXG7wUFIY4GA0F7xfl4oAAOdfgYPo-p+zE+IBXrj1-rjrzBUd+K+IKuIBruuQCMAqmwaiAIoDMAwpgaqRm4FmeoYBSgUEpGSF+nV36oNQY1CafgoDV1rvXPA8D2hJFXtZFQuhiFzXYLSEETcW7gK3r+ce8B64qDQMgLgf8CaTAgMQEGHB0x4HgOkREzC0CGGkBw168cBogFfmgtBjVdDEm-r-PB8DKTxCnNICgmxwG1HVBQAgKVSDXVSJsLRS8H4UAAJyX33ofUxWjIgD1SC-YAJ1JF5VyNIHSBB1oHCGoo2RciP7IEgOYbBP9cFF00TJExMSLEr2JLYyo9j4mn2ss-GRbieaWx-t404fihqhN0kE4JjUW4qGIBQOgRgJH-lFvqZhESVENwoNZM+GizGxJqPILRhi6DGM6eY0+NiN7HycYPChI9qETx7rfWe8z74rzXhvOxR8+4JIoE-VZKSb7zzvpsgcyTr4OP7oPZBb9gnyKCMoqJYBlkqDAB3Ehjdm6tzngvUocz9kcCWavY5h8PkHNPkcjeACpwQNoFAmwqQODMKqbUDgf8GmmHMJwhpyAREwEQCEZFrAxaTAkhcq5JKVCNWKeEnBf9wUdyXr+Vxs0GmTFkNIAqhS7hhNKaS+RpQAgJHMOcbBdBYB-2sHgVgHgAAq+LMZMokrjEAty-5mCCNgSgpQvCwEeRQDAZ8nlZSmVQ0Ex9HhtMyVy7lZTkDECwVS+uZCMCUkaPqohjrnWbG1oq4gsJIg7imn-DeG8nUqCdfC7MBp5B-zvJSZhmw8AGC6n-K0NpIipoFu0SYdR4DDBWfZa1TCZEoMtcWxqqq0ibEpFG5hIRK310pDGkARbi3NtQZsRoUaG0qBCO2ut9cm0tubc+Ss2K-4augDAPtlyB3FqHawbFncJLSF0H-Ro9dhgWunegstKgK1VsVTWvd-bN2krbR26tPaQD1sncemd0hh2IFHXVWA16b3ctnfOwWVAl0rrXRultRSbV-tJUNXl-R5BAfkSsOgQGhoty5UNFqr8EPZFaqNLc40nrHTRhjS6YNPp3VIqbGgeU1U7krIMbQwAi0EzQLhUoux5TSEYEWjFtHiocGXp1A4cszYKxUJoaaqNiNmEQAAUXoNIZA2gMBbTFRKxA0qxZbSyjxuG005NSplcrbQ8qmbcyo2-ATwsNMKZlcHeVXHM7k3fMyIq0Tar1TOGh34RApyHWmsRiALdjrUdekMFQGB+0GeCRJWjlJmNTvfo7G6AApVguhsAAGlnZHpcDwimfCBFCIMLRraVoaJ0EmGACo6XKjTCgMMdo68AD8mDkbEi4ilyLNQ6BeJ8YgXLcWEtNeCdXfJBBcvJYi8E1jAXUvv2C6SllBVcsAlIGAbMPWrlHHGzNVb79psdZujKWUS3gkreazlftB20GTbQaFlQjRhtyOi1tGLulEBqD26g7hvD+GCMRLl-LNpCvFdexl8rlWat1essSZ779PHPna51h74OVB9ehzdNQrBEBw9G4F5rE31vxGCDNm6WpCFPjcPIVH139tk7kWdq5m3ctnQKj-NIWlSBmI6HD9+J2rlU5G7jrbW1ipUFBM+UgRgjBs-WhT9+R2p0HCLdrbABxM7YwAnZ4upcnOKTGrwQGz1ZoEXxZ4XDH0boEbwADTDKhFOJDwzdb6lvoZ4zVZsdzbhEBGC8wYaazTnDY342YmwVBnB65oOAybz56rCv4+qYIYRUZbSpqbd+YfZBQBa54APHM1tTusNITg5guemCoLRpdT5JikAkhzCXxFThF4HqrIdvhhYS0r-9yo73ss15L-X7A1stpN9S5D-rW3i917vQ33v9hK8I+r4WTvo-u+N4n6l0bw-Jj6GQARXSIRtCW8WnH166YqB9+l0WmXtM35J4j-N8mDfxXB8WtYXkVBHBU89gVS2rAe9X-D934Ot-PBhwjijgDljklmAnv3lGnikRpnZy406kzjt1s2qloBLkcyIGcxkAw2d11313AQ2mt1ui8kIwdzcyBk8281uQty000X90DxwMz0TwpmT0jxZRjxugxQT03kYIjzyjTyk2f37Wz1z3oLkQuxXzLzZkX2axpxnxH0kHn3H0rwJgPw71VnqjvW0GwFoUkLQVPxgPlxZAOAOCAA)

### Describe the bug

Hi there,

I'm not sure if it is bug.
How to get original data in updating hook?

$getOriginal() works as I expected. After changing .name I can get original name.

In updating hook are model and record args.
Reading model.$getOriginal in this hook return new data.
Second arg `record` is also new, thus I don't even understand its purpose, when I can get same data with model.$toJson()

So is it bug or how can I get previous data during update proces?

**Comment by CodeDredd** [comment]
Good point ! ... i looked into the code and some logic error. I am hydrating the model with the new data and then i am passing it to the hook which results in this behaviour. Going to change it. So that record is the new plan data and the model if it already exists will be updated after the hook is called.

**Comment by ahoyahoy** [comment]
@CodeDredd 
I'm glad you're alive :) 
I appreciate your work! Thank you

**Comment by ahoyahoy** [comment]
Hi @CodeDredd
I don't like to bother you, but do you have any time frame for when it might be fixed? :)

**Comment by CodeDredd** [comment]
@ahoyahoy Sorry for being so long away. I had to focus on some real life issues.

**Comment by daniser** [comment]
@CodeDredd I guess my problem is related to this one so I won't create new issue.
`$isDirty` method always returns `false` when called from  _...ing_ (before) hooks, i.e. `$getOriginal` return already updated data - as pointed by @ahoyahoy.
Therefore there's no way to know if model really changed or not.
"After" hooks works the same way, but at least it _can_ be understandable.
P.S. checked out edge channel release - second argument now holds old value, but `$isDirty` and `$getOriginal` calls on model still returns wrong results.

**Comment by CodeDredd** [comment]
@daniser fixed it. Now i also changed again back second param to be the data which is passed to the model. (like before)
So to get the old data in `updating` hooks you need now to call `$getOriginal()`
