### ISSUE TITLE
Multitenancy or the ability to use multiple stores and not have model ids collide

### ISSUE THREAD

**Issue by vesper8** [CodeDredd/pinia-orm#1721]
### Describe the feature

In my current use-case I use versioning on my models and I need to use it in such a way where different versions of models have the same ids and can co-exist side-by-side but with different values and relations.

One way to handle this would be by having different versions be on different stores so they can re-use the same models but exist in different databases.

I'm wondering if this is already possible.. is this something that repositories can achieve? And if not.. how much of a stretch would it be to add? Any tips on how I can get something similar to this working right now?

@CodeDredd I'd really appreciate if you could chime in and comment if this is already possible as this is a big problem that's currently on my desk and I have to act on it within a day or two.

Many thanks!

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
@vesper8 Sorry for the late answer. I was moving to another location so i didn't had the time for my libaries.
But to get to your question. Yes it is possible. I thinik there is more than one solution to this.
Are you still interested in one since i am a bit late for the answer ?

**Comment by vesper8** [comment]
Thanks for getting back. I understand you're very busy. I ended up finding another solution to my problem. I'll close this now. Cheers!
