### ISSUE TITLE
optional attrs

### ISSUE THREAD

**Issue by ahoyahoy** [CodeDredd/pinia-orm#1728]
### Describe the feature

Actual data from the database, especially from nosql, do not contain complete data for each item.
I'm not sure how or if it can be implemented in pinia orm.
I need some attrs to be optional, i.e. if I create a new model, so that all attrs in the model are not filled with the default value (which is null), but are undefined.

And null is not even an allowed value for these attrs, so not only is the model normalized to some data, but I can't save it.

I tried to create my own Cast, but if there is something undefined in the data, the Cast value will be always an empty string.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by JeffJassky** [comment]
@ahoyahoy Completed, but no comment or commit? Still trying to figure out how to have optional attrs.
