### ISSUE TITLE
STI Models can only be retrieved through parent

### ISSUE THREAD

**Issue by Sayanel34** [CodeDredd/pinia-orm#1735]
### Environment

Playground

### Reproduction

[Reproduction](https://pinia-orm-play.codedredd.de/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDscQLh2bxOcN3AlZcgKBAfPzXkK7cJmN9JOL-rwAJLqxAVBVJYK6eK6NJasOsCM1DizQtpSBIc29frW9EJh3YhahxDEcMGSPRujnABsk0antWwwZXsQ22ZrIDpyIPiyEFjgveCZF4hTiqIAAUzHRl8xug3UTaMa3houD+cR5TJgPQ3RkNJL-uIPTkHgKOVWNFs76WX9QMznOK8IAoOo5mwSDDDoAAvDgVzeXhhSTUUtwlXc3xUAB5AAlABZFRoI4PBYIQ+tkUbNFbQmC9QLfCDSOGEiyKCBDzjvAB2clH2fSdtj2P02TOXBoLoKgWPkCgbigThCGYF5VxQ9c0M3X5MN4AA5CBxKeI9ERPJtaPtLEWN01gJPOAAWD0ySk7AZPleSBIA2dgIXRjIKQ+MJg3MVt14Pcl1wwjKMtaizxbMywKYvBOMmHj7KoJ8Xw2KcdhnABdZgjDoAwzTQUAAEEwDASYFnQUBUl1AwIFSIgAB4UuIAA+AAdcwVGa7IOq6lRut0dpWp3bM2GwbA0gIupDDSPDED1A0Eg4EJGuGIa+oGgaeuIFRiAoWoOAAXnakBtDAMb5Em6aKgKxhTFpKdHDMFQLtyK7EBu2adTAAIQVOlQ0BgRAQhOkB0s2U7Nq27awFa4BgFey6Js+maCsmCSVAOA41rhzqYdh+HEbe8brrRxB6WwG46HgSasZxy9oZhxq4YRpH3pRr70YqJ95ABVgoAPAr6dxpnusfNr8fFlroca3QOFlmWpe2jbRo5umd10EIDQAR1UebFuCOpVvW4ble6lq9oOuowfO5HJs17W6D1xB7oh57zBJj7Hd18gfr+qgAaBkGwYhqHzcJtmvZRn3nfIDHQWx0WI+61niftxBY5dynqdptIk8ZlOWaJ9nSczrXfYpnnxv5wXZpFwv+ul3qpbWpWurlhXW-b5nVYzlQDf1I2VrWjbzZ2q3Dtt6PJrdx7Ng90uPv91JA5AQHgdB06w5AMXI-T9WKcxgu8ab-el5RnPEBpumT731OS5nquIF57Ba6F-OGdPgmH6jjPJmgngBu38CbFz-ofSYYBrCAOAWLNuLcO4S1lvLPq8C2rPACkQOguo6jSBUIjLEv1V5YwrFWAA5AsMhnVsF6g4HgxG00aAGHuniQeJCjCViAWQ2KkEqHYE6lAOqyBnBqzLioKcqRaTOEYZ4fBUtnz1ToFAcR6pghhCOioU6oiPqnQANzyOkIo5RUDsGVBCAAaRBioDRp1zgST0QYox8QQgXUseozRFxQgXQcfwrqCjZDKK8SgbQjhgApwGtYaQnBzBhLPj-FQ2iUZoASRnRg4SCaJLJrdRAyTMmo2yWkuJP88lZ3ILkjOpTEDpIOObGpviBr+KUTUWEBgqDIBCXIpukTomdPiR4uxa9knSF0E+SYz5JDYHgCEwpfTbFBNOkMkZyAxnSAmVM+wMz4kSUWaM7ApA8ClGzCE2pUs6l1IEUIkRFSK5xzSBImwbSUmH16SoRpyibCyFCNYjxJSbkux8Q0wxASVClAgDcAAoqor5NiQB5J8Y44FeVPBtJCbEmG3SOAxJTpMHFyBSBvUmEi1p7SNkpygTYWYOzlnjN8NMlOgCqUrLWccpudSBpnM6hcsFVzD5czuZsSRjy8kvLeSoz57itEZz5QC15QKmmgohVCiVsKM7wr8XK5RRKUX2DRVtDFWK4k4rGfi-8WqSWbJhjYXOk1GU0smXSuJ1c+YCw-ra1ZtLSVxNWJ4AqbrmX2BOV1DlviZhUzwU-Pl3zdW2PsegDxww+yXgzgAfTwOTZAwxKSnU2XMlxVS42St5eTbNUtt6DJUJSHNIArXXzzgsjxAAha4ZhVQlq6qdJ1b8XWzXradAEJqOCnU6uc2w8hnwXwdn81QGjo0XFjck06CafBJsPsmsAU6UCZrbQNXN3iC0qsPpU7dHj50qEaFW8lgDe0gAAFKsF0PwpgpaAyzGvWoVg+bh2ctHWGid+TZpsI0awharBtB5L5fYfRP7x1P0qYB-wNxB5geuU7F2kGBFjvDRneDwG9TIcPuh3xEbyaDzGRADwdsi3ZMI7BjdpG8gUdo6h8ghGMO-qY5XFeIJvmEIDtoDpR1oYcduaRwwBgWWseg1hqj31ZhEO4xo3jq9+OOEE1LYj2TRMRAk1BtjMGM5cdBIpuTfGBNCewyByYYmdMsmxkAA)

### Describe the bug

You can't retrieve data from children model, only through parent model.

**Comment by CodeDredd** [comment]
Hmmm good catch. Need to look into it.
