### ISSUE TITLE
Model's data not populated

### ISSUE THREAD

**Issue by olinox14** [CodeDredd/pinia-orm#1751]
### Environment

> See on stackblitz

### Reproduction

<https://stackblitz.com/edit/nuxt-starter-mhusga?file=app.vue>

### Describe the bug

I've got a custom model extending the pinia Model class. When I create a new instance of this model, either using repo.make(data) or the constructor, the resulting instance is empty : 

```
const data = { id: 123 };

const repo = useRepo(MyProfile);
const profile = repo.make(data);

console.log(profile);
```

results in : 

`MyProfile {}`

**Comment by olinox14** [comment]
**Update**: it turned out that adding this to the nuxt.config.ts solves the problem

```
vite: {
    esbuild: {
        drop: process.env.DEBUG ? [] : ['console', 'debugger'],
            tsconfigRaw: {
            compilerOptions: {
                experimentalDecorators: true,
            }
        }
    }
}
```

**Comment by CodeDredd** [comment]
related to #1610
