### ISSUE TITLE
Enhancing typescript safety in model class by removing generic property declaration

### ISSUE THREAD

**Issue by joris-gallot** [CodeDredd/pinia-orm#1759]
### Reproduction

I don't think we need a reproduction link for this

### Describe the bug

The `Model` class has this line `[s: keyof ModelFields]: any;`, which I think is problematic because it allows us to use any property of the model without typescript errors. I think we should remove this line. Is there a specific reason for keeping it?

For example for this `Foo` model, we should get this ts error: `Property 'bar' does not exist on type 'Foo'...`, while in the example, `bar` is typed as `any`
```ts
export class Foo extends Model {
  @Uid() id!: number;
}

const foo = new Foo();
foo.bar; //  typed as any
```

**Current behavior**
![Capture d’écran 2024-01-10 à 10 13 36](https://github.com/CodeDredd/pinia-orm/assets/70059224/550890a5-6b6b-4ced-b024-42d2593c0b0a)

**Expected behavior**
![Capture d’écran 2024-01-10 à 10 13 54](https://github.com/CodeDredd/pinia-orm/assets/70059224/77220784-555a-4b41-b348-d8173354a872)

### Additional context

I'm putting this issue here for discussion, but I can tackle this task if needed 😁

**Comment by CodeDredd** [comment]
Good Question. I don't know yet. I am not a typescript pro. I try to play with your idea to see if maybe i get any caveats.

**Comment by joris-gallot** [comment]
Thank you!
I've already quickly tested removing that line to see if there was anything blocking, and I didn't find anything special. If you need help with that, I'd be happy to offer a PR when I have some time 😁
