### ISSUE TITLE
userRepo.get is not a function

### ISSUE THREAD

**Issue by khamaileon** [CodeDredd/pinia-orm#1776]
### Reproduction

https://pinia-orm-play.codedredd.de/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDscQLh2bxOcN3AlZcgKBAfPzXkK7cJmN9JOL-rwAJLqxAVBVJYK6eK6NJasOsCM1DizQtpSBIc29frW9EJh3YhahxDEcMGSPRujnABsk0antWwwZXsQ22ZrIDpyIPiyEFjgveCZF4hTiqIAAUzHRl8xug3UTaMa3houD+cR5TJgPQ3RkNJL-uIPTkHgKOVWNFs76WX9QMznOK8IAoOo5mwSDDDoAAvDgVzeXhhSTUUtwlXc3xUAB5AAlABZFRoI4PBYIQ+tkUbNFbQmC9QLfCDSOGEiyKCBDzjvAB2clH2fSdtj2P02TOXBoLoKgWPkCgbigThCGYF5VxQ9c0M3X5MN4AA5CBxKeI9ERPJtaPtLEWN01gJPOAAWD0ySk7AZPleSBIA2dgIXRjIKQ+MJg3MVt14Pcl1wwjKMtaizxbMywKYvBOMmHj7KoJ8Xw2KcdhnABdZgjDoAwzTQUAAEEwDASYFnQUBUl1AwIFSIgAB4UuIAAdcwVHgSQqAAXlakAAD8aiiCgZgMTrowoaz+valQVDAOruD6kAZizdVRpsVJ6mCWhI24LMOBmjrdGWzdEBsI65tqdVlrweRWEulQAD5ZpUZrshUKA6uQZBbrMChIgoDB2jJMkwE2LL+pejq5sam4CtzYgKDumgDGWvEOABTx5WkfrPu+37+rwUoKAADhUUovFgeaQgoEdiXmzYKDJJIKCMUgIniKdpBkvAuc2HmuogWniVBin4AoaQKmwZBIGsdUKbqGgOGZxWOGV786bVjWhdpxoxejMBEEqXTuAoaDsDSKhKhgNBUgFihdamsXrY4W3SiV7NHYqWmuLF2o5KGdhpCCS3zfkNIA+uNBJGwCWWajoYPfVr2nf1lmjezKHXrm2HvEVFQ0GIQxyGW7AOYMPH4ZxkEnq0iPGuGfOJWh3Pc8a5ujSR2oOHRm5tvMDHkDxouS8QPv-wkkeYEQEIJ44SYp5AJ7gGAfx+8mYCVAOA5G877BW-bu5sYVQ-YYx0bKlBJG6CMU6T9SKg1HqiAR4x++Ecf5-pFfkBC4SKg+oP41yfi-SYAD9R43ONYO6HgAAqrBAHLRgaweBiCHp-2GGfN6LUVBI08JCL6EAfp-UcroIG7RRbg0hsvRuLVD50OyNDRhxAnrPACkQOguo6jSBUGvawRhGCfVmGAAIIJt4VirAAcgWFI9qXC9QcF4WvPEeFEB6gkUYSsfMpGxUgnIrI3ClEZH7pInRkxhgQn-PsAxCieEqAQYAsxKgpEWMcawX0tijG8Otj-ZxrjQxgJsfI7x69sxSivv4ixGMInqwquQAx7VVrPjCRwNRGiephPSawbQViOD2CSfIFJEDskqEyao9ROT3EFOwIUmWvCMZY0-mUlQAjtDlwiDU9qGNsmTDyB4bQvj3xDy6bYIpDT+7OEyViURj9tDaEcD1J6qTelIGkAs0ZyTeHVwVCCb+rhpkiLEVQeZizllDwqmPSYeVaTaAxmU85G8JJlJ6uU-uTScaXIMOQewmzxmtNoKgxA7iWnaAkmcvhr0SmVMmGIKWrAQhgqoDUg4gE+D91iVQeJPBqq0AWvVM471iD42IYTEAgN2aczIkzQGn5xYA10DtVp7BaQggoAYPwydlba1Tj7OmYsCSAMBngUErt3YSydqTF2Ns0Bct5cLCgfsyTZxhjgj6RCSH9SMAVTYw0pyjVlKYGqe1NrZnmiTSkyrl45zbm9LhfgNVkuJhQdorNGjWRUOQ91zL+A0CoGzCuKhBW-nZfAEeyAuDz0mBAYuP8ODpjwPAdIiIR6GGkFG4CKrbXt10AzR1t0LX8x5psca10eYEBSqQPm9tBZ8oAJzSrdnbbmDKdpQ1Xqk65dBcjSB0gQbeu9hi5uwW3OGkBzD5v6jW3mRbvYKtFizMVzaHZO2sqDdtKiN7fV7acAdjdZa6RHe3DmeCKC3yjRA4ef9J3kqmuTaddKy3IxBHQKts6nYNpZqUCWkRGWpB9ay-1HKeX1DlSrNOjbxVzt9pB2VntwN8oHLB6dv623WtVdm2GQQSWavAHrRmU1WaUvGmB78IHoP8sXTK0jTskMJx1Ua3aG0Dp427nUZaEDTCDw3pe6es8OPoMXlQLNmHRNjt0jhsl2r9VdV-Bu+IgnZAhzSDvfd46j2idhqUAICRzDnC+nQWAyDAVoMAdoCBQmCnXoJstMwodKCU1YNTMAQNSbUIA36+ljxnZWo05p0dyBiAOps-1chGBKSNHc4DcLkWIasdhJEHcPDlosxZhFlQEXWPZgNPIZad5KR402HgAwMtlpWhtJESrkxIjtEmHUeAwx072UC2G9D-n2vt3syoTYlI8t4xCL1-qlICsgBtR18b3XGh5ZGyoEIU2huPQmxN58lYZ7LUptAGAi2lsdZW6wGeAMJLSBOv1Ro-UsFjZ251swaQet9b-gN+7l2ruYc2PNkAw3+vvc+6NjDL3MN7bW-1DbsBtv-YB-Cg7kQjsnZAGdkAF2-sTf3UFvzYnhjaf6PINHR8gh+cbhzbBLDmGPlYewrcnDQmbsQKUg4-i9GkUSaym5iAdyVkGNoYAr0MZoFwqUXYONGBQvQUMFQxUOA+3agcP59SVCaF4ZkmgLOACi9BpDIG0BgKRKDTOsCkVlGXKSdfAvQaC8FDzIUdXl9obXJmTeAKkUI8FUu0VDIAkVEANV8UNV4OT34RApyKJ8YgIwEAObKO55M3nGAbVc7+xJXnlIhd-eArzqRAApVguhsAAGlHeXZjS-eNibk0GDT1aGidBJhgAqLGyo0woDDBBmSAA-PanqxIuL57+3lHtfbEBp8z9n7v2bt397T3n5P2bL3R+e5b-zSmCpp4BKQI2HAR+YaOHPuPC-ghL5cTKWUG-s1b7+zlG1p+2479tQnlQjQp+2tTy49PulEBqGP7nQvcaE1JsROXyKowVeNeX+9eUAjezebeiaPU1kxIH+V03az44+z+r+cBKgY+pwaeagrAiAqBM+KgMeSO8+mmi+A+LiWorqT4bgEcqBc0l+mG1+omJBaeaiBUxCaQWkpAAsHQNB28D+2aDBmGTBLixUVAoIz4pARgRgPBdBbc5+qqBwr0kM2AqKRwIAeS7uuKtUBKRAfuMglOQefCKgBEiCngmi2iLiDOeAXiBhIKWi0ibigmwStSlsmwBhSuYeBgvCjqJiZq3MNgVAzgxhqMRBz49Uhmcu6owQYQmSUiQ8TOc0oRsgUANQsIBgARCyRBc01g0gnA5gAhc0t+x2T4kwpAEkCyfBucT+RRyAfSUsvgNuUi9gFRc0IBxev+ZehYxRK29RUijRzRKRfeGBnRNR3RccDRTRl26BBAvO1RtRsc8A4x-ReBsx+gyABEukiK7iQisR-c6YVAfRF+r0ChyhaK7iGhnueKdUPuIAuh0g+h9ia8QRphdOdhOilhTOge9i7h4ekmDipufhtIgRJh401+iR4Rm0URLSUil68RQaP8SRKRng6RjgAh2RuRmRuchRjKNRpRJyExf2QhsxoxCxvR+J2aGMexMx2J0a-QHA7SFcZJucxxtBLuO8BwQAA

### Describe the bug

Doc says:
```
Note that the retrieved models are indeed the model instances. Not the plain object. For example, when you call useRepo(User).get(), you'll get a list of User model instances as a result.
```

userRepo.get() give me:
```
userRepo.get is not a function
```

I also notice that userRepo.orderBy("name").get() returns all users with related data, as if I had done all()

**Comment by mariusgnicula** [comment]
For me using Nuxt 3 with Pinia ORM, I have the same issue, where .all() gives me an error that it doesn't exist, but your orderBy "solution" is working for me as well.

**Comment by vesper8** [comment]
Have you tried `userRepo.query().get()`

**Comment by CodeDredd** [comment]
`userRepo.query().get()` === `userRepo.all()` === `userRepo.where().with()....all()`

`get()` is only for querie chains. 

Maybe for v2 i remove `all()` and add `get()` to repo. But i don't know yet if that makes sense.
