### ISSUE TITLE
Axios Plugin - Ability to set a custom header globally, and them modify it on the fly

### ISSUE THREAD

**Issue by vesper8** [CodeDredd/pinia-orm#1787]
### Describe the feature

Currently if you set a global custom header like this

```

const piniaOrm = createORM()
piniaOrm().use(createPiniaOrmAxios({
  axios,
  headers: { 'X-Custom-Header': 'CustomValue' },
}))
```

If I would like to modify the custom header on the current instance on the fly, is it currently possible to do this? If so.. I would very much like to have this feature added.

Many thanks!

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
https://pinia-orm.codedredd.de/plugins/axios/guide/configuration#request-configuration
