### ISSUE TITLE
BelongsToMany Relation is not deleted on save()

### ISSUE THREAD

**Issue by aflatscher-loop** [CodeDredd/pinia-orm#1794]
### Environment

playground
https://pinia-orm-play.codedredd.de/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDscQLh2bxOcN3AlZcgKBAfPzXkK7cJmN9JOL-rwAJLqxAVBVJYK6eK6NJasOsCM1DizQtpSBIc29frW9EJh3YhahxDEcMGSPRujnABsk0antWwwZXsQ22ZrIDpyIPiyEFjgveCZF4hTiqIAAUzHRl8xug3UTaMa3houD+cR5TJgPQ3RkNJL-uIPTkHgKOVWNFs76WX9QMznOK8IAoOo5mwSDDDoAAvDgVzeXhhSTUUtwlXc3xUAB5AAlABZFRoI4PBYIQ+tkUbNFbQmC9QLfCDSOGEiyKCBDzjvAB2clH2fSdtj2P02TOXBoLoKgWPkCgbigThCGYF5VxQ9c0M3X5MN4AA5CBxKeI9ERPJtaPtLEWN01gJPOAAWD0ySk7AZPleSBIA2dgIXRjIKQ+MJg3MVt14Pcl1wwjKMtaizxbMywKYvBOMmHj7KoJ8Xw2KcdhnABdZgjDoAwzTQUAAEEwDASYFnQUBUl1AwIFSIgAB4UuIFRhgAPmeAKiDoXU6mkFRgAI1gaAMRh-BuPDED1A4KyrAByWLIPmgAdbA1qgOrkGcAFpEqWRsHgHdLPVFQp1SWlnGG0bBrWlQVGfeq6CgM71WCMIAF4VHmx6OAOo6TukABRN7TWQVb1vMB69tkF68s8KhkG0RxgDu+6VGsaROHMVGofR0wqDQQsn0mbBSDwUps2Rxg0fx4CiekXQSefSRDup2n0dSfAhmJ5BJn0ZACN0kJtAAFUQfBxp+va-t8Y6zGkdMqHm+wabxlQDjRzXsG1jatuccX8DOzYLsRlRrs8W6oce2HXtkUIVC++aubwEH7dhcG1rRm3npqWEDER5GrfxzHseD-GCYZpm+bJimqdVjn7vp3nJhZ3x2fV+7fv++X1SjknKa8Q7kFF1htF2-a5cBqXs6rhWlZVtWI+hyvDtzxXCZT2PKY4DP8e1+7td12x5GfeIJbwKa9UdibECnsvDbwewvazfB59TiAPG0XH7okonKSb4jTiJ+bF5USl5sP2u28Bomd-Rvfz8PpPj++ivZcOlR2-Py+tbVg5l6QxmNgNgBVJheHgNoF269Ij5m0NLVuAMFYq0mHlWk2hKT2FTjLHOgNAGjEdu1Qaj8D5HwICfd+-0v6Ax-sPAhosOAhF8PERIeQPAY08E9I0sDGbEVIBEFQxBDDkHGgkYiiRN4QHymtaB01WAby3vfEhh9k6nwnj-K+OC655z4REf+gCNqj1lIgcBrBIGyL1JMHhuh4HXyQeqFBaCqAYKwXY9u+DhiEOIZ3UhqjKHMO-hfOhniASb2YbUawdB4DmBgIgMI1jdEGEEcItIkQ6gwGQDIie682GIG3mjZRaNVFnwvpoxB7clZEzJnotaACV7ANASYiBUDslyKsXAhBH97HSEcRsFx2Dyl4LWgQj6RDqkGDWiyA4BwgA

### Reproduction

```js
import {Model, useRepo} from 'pinia-orm'

class StartingPoint extends Model {
  static entity = 'startingPointEntities'

  static fields() {
    return {
      id: this.number(),
      name: this.string(),
      teams: this.hasMany(Team, 'startingPointId'),
    }
  }
}

class Team extends Model {
  static entity = 'teamEntities'

  static fields() {
    return {
      id: this.number(),
      name: this.string(),
      startingPoint: this.belongsTo(StartingPoint, 'startingPointId'),
      startingPointId: this.number(),
    }
  }
}

const teamRepo = useRepo(Team)

teamRepo.save({
  id: 1,
  name: 'Team 1',
  startingPoint: {
    id: 1,
    name: 'Starting Point 1',
  },
})

console.log(teamRepo.with('startingPoint').find(1).startingPoint)
// => {id: 1, name: 'Starting Point 1'}

// Trying to save relation with null value, to no avail
teamRepo.save({
  id: 1,
  name: 'Team 1',
  startingPoint: null,
})

console.log(teamRepo.with('startingPoint').find(1).startingPoint)
// => {id: 1, name: 'Starting Point 1'}

// Saving foreign key with null value works
teamRepo.save({
  id: 1,
  name: 'Team 1',
  startingPointId: null,
})

console.log(teamRepo.with('startingPoint').find(1).startingPoint)
// => null
```

### Describe the bug

Saving a relation with a null value, does not remove the relation. As you can see on the second save/console.log, the old startingPoint is still referenced by the Team entity.

Expected behavior would be that the relation is removed, like when you overwrite the foreign key field with a null value (3rd save/console.log).

Is there a way to configure the relationship to actually be removed like described? I looked through the documentation, but couldn't find anything.

### Additional context

I do not expect the StartingPoint to be removed from its repo, but the relation between Team and StartingPoint should be removed.

**Comment by CodeDredd** [comment]
This behaviour wouldn't make sense. This behaviour wouldn't be consistent with other ORMs.
Saving something shouldn't delete a relation. Changing the stored relationId is the only way and will be the only way to remove relations with the `save` function.
