### ISSUE TITLE
Getter from custom cast is not executed when accessing related models

### ISSUE THREAD

**Issue by vesper8** [CodeDredd/pinia-orm#1849]
### Reproduction

related to https://github.com/CodeDredd/pinia-orm/issues/1818

### Describe the bug

I'm using a custom cast with one of my model fields and that cast provides a getter and a setter.

I just noticed that when I load related models, the getter is not being executed. It is executed fine when I query the model directly but not if I load a parent model.

So here it works well

```
const requirements = useRepo(Requirement).all()

console.log(requirements); // here the cast is applied and the getter is used
```

but here it doesn't

```
const architectureView = useRepo(ArchitectureView) //
  .with('requirements')
  .where('id', this.currentArchitectureView.id)
  .first();

console.log(architectureView.requirements); // here the cast is not applied and the getter is not used
```

I believe this is a bug right? If it's intended.. is there a way to circumvent that so the getter is always used?

Thanks!

**Comment by CodeDredd** [comment]
Yeah i think this is a bug. Looking into it.

**Comment by vesper8** [comment]
@CodeDredd Great thank you!

If possible I would like to know if you foresee being able to push this fix to the edge channel very soon? I ask because I'm working on a demo for next Monday and without this fix I can still make it work but I have to add quite a lot of extra code to do the work of the getter in many places.

**Comment by CodeDredd** [comment]
@vesper8 If you spend my a ☕ i push it very soon. 😉 😄 ... i like brain motivation. ^^

I see what i can do. 😉

**Comment by CodeDredd** [comment]
@vesper8 Many thanks ❤️ ❤️ .  This is enough for 3 coffees. So that's enough for one day 😆 .... hehehe....
not thanks. It's always nice to see to get something back 💯 

I hope i was fast enough with the fix....hehehe ^^....it seemed only to have affacted `belongsToMany` and `morphToMany`

**Comment by vesper8** [comment]
@CodeDredd Thank you very much once more! I can confirm that your fix is working on the edge channel. I was indeed having this issue with belongsToMany relations.

Cheers!!
