### ISSUE TITLE
Inconsistency in has_many_save_uid test ?

### ISSUE THREAD

**Issue by oaubert** [CodeDredd/pinia-orm#1875]
In
https://github.com/CodeDredd/pinia-orm/blob/5813664d03e46a86a9ffb0e13dc4d51c8e211fb4/packages/pinia-orm/tests/feature/relations/has_many_save_uid.spec.ts#L17
the `userId` key is declared as a number, while the declaration in the User class states that it is a uid (string): `@Uid() id!: string`. It looks like an inconsistency.

**Comment by CodeDredd** [comment]
You are right i defined the wrong type for userId. Not all tests are perfectly written 😉
