### ISSUE TITLE
Pinia setup store syntax support

### ISSUE THREAD

**Issue by jhercog** [CodeDredd/pinia-orm#1888]
### Describe the feature

The title says it all.

Would you consider supporting [Pinia setup stores](https://pinia.vuejs.org/core-concepts/#Setup-Stores) syntax? Currently, pinia-orm supports only the [option stores](https://pinia.vuejs.org/core-concepts/#Option-Stores) syntax. Using setup stores would provide much more flexibility, allowing us to utilize watchers and composables inside the store itself. Not to mention, this intervention would make the plugin more compatible with Pinia.

After reviewing your code, it seems relatively straightforward to implement. As I understand it (though I could be wrong), the main change involves how the plugin uses the `useDataStore` function.

Here’s the current function:
```javascript
function useDataStore(id, options, query) {
  return defineStore(id, {
    state: () => ({ data: {} }),
    actions: useStoreActions(query),
    ...options
  });
}
```
To support setup stores, the second argument in the `defineStore` call needs to be a function that returns an object with reactive properties and methods. There is also an optional third parameter representing a custom options object for additional plugin configurations (e.g., pinia-plugin-persistedstate).

The modified function could look something like this:
```javascript
function useDataStore(id, options, customOptions, query) {
  return defineStore(id, () => ({
    data: ref({}),
    ...useStoreActions(query),
    ...options
  }), customOptions);
}
```
As a starting point, perhaps you could provide a way to override this function? You might consider including it as a method in the Query and Repository classes so we can extend those classes.

Regardless, I must point out that you are doing a great job in creating and maintaining this plugin, and it is already excellent even without the proposed feature.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
Well the code part is done. Only the docs needed to be updated. But i don't know yet because the solution adds also 4KB to the bundle size.

**Comment by psarin** [comment]
Hope this makes it in soon. Would be extremely useful.
