### ISSUE TITLE
Pinia ORM axios

### ISSUE THREAD

**Issue by raizdev** [CodeDredd/pinia-orm#1901]
### Environment

Vue 3 + Vite 

### Reproduction

https://stackblitz.com/edit/vue3-vite-starter-7hutpf

### Describe the bug

What is the correct implementation for axios in pinia orm? I followed the documentation on the main website but i dont get it working. whatever i'm trying..

retrieving [Pinia ORM Axios] The axios instance is not registered. Please register the axios instance to the repository.

### Additional context

What is the correct implementation for axios in pinia orm? I followed the documentation on the main website but i dont get it working. whatever i'm trying..

retrieving [Pinia ORM Axios] The axios instance is not registered. Please register the axios instance to the repository.

**Comment by nowrap** [comment]
Hello,
if i use the new implementation with vue 3, vite and typescript, i get still this error (npm  run dev):

> Error: [Pinia ORM Axios] The axios instance is not registered. Please register the axios instance to the repository.

This is the store implementation:
```
const pinia = createPinia()
const piniaOrm = createORM({
  plugins: [
    createPiniaOrmAxios({
      axios,
      baseURL: 'http://localhost:3000',
    }),
  ],
})
pinia.use(piniaOrm)
```

If i run "npm run build" i get an other error:
> error TS2353: Object literal may only specify known properties, and 'plugins' does not exist in type 'InstallOptions'.

Maybe someone has an idea?

Thx and regards
nowrap
