### ISSUE TITLE
Axios `baseURL` is lost most of the time

### ISSUE THREAD

**Issue by daniser** [CodeDredd/pinia-orm#1938]
### Environment

playground

### Reproduction

https://stackblitz.com/edit/vue3-vite-starter-dzaynw

### Describe the bug

`baseURL` is not utilised during queries from Axios repository.
P.S. Looks like `dataKey` is affected too.

### Additional context

Current workaround is to provide full URL and data key directly in query.

**Comment by CodeDredd** [comment]
Hey. Thaks for the issue. This is fixed with https://github.com/CodeDredd/pinia-orm/commit/29a91b0. 
You can use the nightly releas to try out. It will be fixed in v1.10

**Comment by daniser** [comment]
> Hey. Thaks for the issue. This is fixed with [29a91b0](https://github.com/CodeDredd/pinia-orm/commit/29a91b0). You can use the nightly releas to try out. It will be fixed in v1.10

Unfortunately, issue still persist. I've updated my reproduction with latest version of the package but nothing changed.

**Comment by CodeDredd** [comment]
@daniser Did you also update the axios package?

**Comment by daniser** [comment]
@CodeDredd [yes both `axios` and `@pinia-orm/axios`](https://stackblitz.com/edit/vue3-vite-starter-dzaynw?file=package.json).
