### ISSUE TITLE
Failed to resolve import "vue-demi" from "node_modules/pinia-orm/dist/index.mjs".

### ISSUE THREAD

**Issue by kimchristiansen** [CodeDredd/pinia-orm#1963]
### Environment

I am using  pinia 2.2.6, vue 3 composition api and node v20

### Reproduction

Update to pinia-orm 1.10.0

### Describe the bug

I made an update to the new awesome version 1.10.0.
After the update to the new version i get the follwoing error: 
`[vite]: Rollup failed to resolve import "vue-demi" from "node_modules/pinia-orm/dist/index.mjs".`

**Comment by CodeDredd** [comment]
Can you make a simple repdroduction pls 🙏 ?P

**Comment by kimchristiansen** [comment]
Installing the package did work. Thanks alot for the quick answer!

**Comment by sanderdatapas** [comment]
Thanks for providing the workaround, we also run into this issue. Just so we know how temporary the workaround should be, is there already a vision for a permanent fix within this repository?
