### ISSUE TITLE
How to use mapRepo in composition API?

### ISSUE THREAD

**Issue by MHassanSaqib** [CodeDredd/pinia-orm#417]
### Describe the feature

I am facing data loss when I negivate to another page. I am using composition API and defining the following code on each page where required. 

```
    const pinia = createPinia();
    const profileRepo = useRepo(Profile, pinia);
```

Is this re-iniitating code causing the data? How can I persist models data while navigating back and forth on page? 
How to use mapRepo in composition API? 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [ ] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
1. Don't use createPinia on every page. You need to create that instance only one time. Thah's why you loss data.
2. `mapRepo` is only for the options API because in the composition api it doesn't make sense to have it.

**Comment by MHassanSaqib** [comment]
I am using Quasar Framework. The store "the index.js file inside stores folder", this is framework generated file and I have just included the pinia-orm in the boilerplate as per documentation: 

```
import { store } from "quasar/wrappers";
import { createPinia } from "pinia";
import { createORM } from "pinia-orm";

/*
 * If not building with SSR mode, you can
 * directly export the Store instantiation;
 *
 * The function below can be async too; either use
 * async/await or return a Promise which resolves
 * with the Store instance.
 */

export default store((/* { ssrContext } */) => {
  const pinia = createPinia().use(createORM());

  // You can add Pinia plugins here
  // pinia.use(SomePiniaPlugin)

  return pinia;
});
```

If I do not initialize the Pinia instance then my code is giving the below error:

`Uncaught (in promise) ReferenceError: Cannot access 'pinia' before initialization`

I am still figuring out where I am making mistakes. Do have any suggestions or opinions from the code snippet above?
I have recently switched from options API to composition API.

**Comment by MHassanSaqib** [comment]
My bad, I must use it like the below snippet. and then import it into pages.

```
import { store } from "quasar/wrappers";
import { createPinia } from "pinia";
import { createORM } from "pinia-orm";

/*
 * If not building with SSR mode, you can
 * directly export the Store instantiation;
 *
 * The function below can be async too; either use
 * async/await or return a Promise which resolves
 * with the Store instance.
 */

const pinia = createPinia().use(createORM());

export default store((/* { ssrContext } */) => {
  // You can add Pinia plugins here
  // pinia.use(SomePiniaPlugin)

  return pinia;
});

export { pinia };
```
