### ISSUE TITLE
TypeError: attr.setKey is not a function

### ISSUE THREAD

**Issue by MHassanSaqib** [CodeDredd/pinia-orm#426]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `npm@8.5.5`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I just change the primaryKey name. And start getting this error. Now, I changed the name of Model from Pagination to Paginate, everything is working fine. There must be some caching strategy that is causing this bug. 

### Describe the bug

```
TypeError: attr.setKey is not a function
    at Pagination.$fillField (index.mjs:1609:98)
    at Pagination.$fill (index.mjs:1586:27)
    at new Model (index.mjs:1383:18)
    at new Pagination (Pagination.js:4:16)
    at Pagination.$newInstance (index.mjs:1542:12)
    at Query.checkAndGetSTI (index.mjs:749:70)
    at Query.hydrate (index.mjs:738:93)
    at Query.saveElements (index.mjs:643:120)
    at Query.save (index.mjs:632:13)
    at Repository.save (index.mjs:966:25)
```

Getting the above error.  The model is as shown below:

```
import { Model } from "pinia-orm";
import { UidCast } from "pinia-orm/dist/uuid/v1";

export default class Pagination extends Model {
  static entity = "paginations";
  static primaryKey = "repoName";
  static fields() {
    return {
      id: this.attr(""),
      repoName: this.attr(""),
      indexOrder: this.attr(""),
      nextPage: this.attr(""),
    };
  }
  static casts() {
    return {
      id: UidCast,
    };
  }
}
```

At first, it was working fine and then it start throwing this error. Not sure what is causing the error.

### Additional context

If there is some caching strategy, we can remove the cache on server restart or on some sort of watchdog event.

**Comment by CodeDredd** [comment]
Would you provide a [reproduction](https://v3.nuxtjs.org/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by CodeDredd** [comment]
@MHassanSaqib I am closing this now. Feel free to reopen if this bug still happens and is reproducable. Thank you.
