### ISSUE TITLE
Single Table Inheritance not working when retrieving data

### ISSUE THREAD

**Issue by hsm22** [CodeDredd/pinia-orm#471]
### Environment

Recreated in the pinia-orm playground. Same issue when setting up locally.

### Reproduction

[Pinia-ORM playground demo of issue](https://pinia-orm-play.codedredd.de/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDscQLh2bxOcN3AlZcgKBAfPzXkK7cJmN9JOL-rwAJLqxAVBVJYK6eK6NJasOsCM1DizQtpSBIc29frW9EJh3YhahxDEcMGSPRujnABsk0antWwwZXsQ22ZrIDpyIPiyEFjgveCZF4hTiqIAAUzHRl8xug3UTaMa3houD+cRxTKQAOUN0ZDSS-7iD05B4CjlVjRbO+iy-qBmc2B1Hghh0AAXhwK5vLwwpJqKW4SkQYEcBBQQwfWyKNmitoTBe6GYdBHDnO0kxDo0T4vsMxGQTBn6AbOIFoRAYF0FQdHyBQNxQJwhDMC8q4IeuSGbr8qG8AAcuxrCcThlp4WeLZYnRcmcecAAsHpktx2C8fKAmTtOfpsmcV4QBQ4FwfGEwbmK268HuS4qAA8gASgAsopVr4eeamWdZGHnJSukUFwkzEjRr4bFOOwzgAuswRh0AYZpoKAACCYBgJMCzoKAqS6gYECpEQAA8VDZAAOuYKjwJIVAALw1SAAB+NRRBQMwGA10YUFpbV1SoKhgKV3CtSAMxZuqPU2Kk9TBLQkbcFmHDDfVuhTZuiA2Jto21OqU14PIrAHSoAB8I0qFV2QqFApXIMgJ1mBQkQUBg7RkmSYCbIlbXXdgN2jaNFVBCoaAwIgIRTWA2ZsNgkycW1KjEBQtQcHDCNGmYY049gyCAyDoPAMA+O5EaBwHCTFUrHQQMk2DENQzDU0QFQpAGNIyNUKj6OY+znPc6Y5gc1z0hEyAQOg6T5PiyL1O0-TjP1WDYDWJdZMK5LHmIHq1N0xriCq2DT7EEDdPVRbzyOUQdC6nU0gqOT1hGIwD2zGAAQgioBwVlWADkCyB3VDt6hwzvk3iet6n7Ad4CogdBeBodZI7kcuzuBMe1lwvO-7RiVongeTMMEIAfsad1XVM0vhTiOx4kzX+DcTfaNnlPYPYtfyPXOtNyoLcx-rrDaHnEs98D08D6Pkx5B42gYDd5OcWgKiUh7IHr4HABSrC6OYaisIggce7srClDvALKtIkSEioACi2DwGYe0cIHft1YlU91fDXdN3nhARey96qryoOvRoW9Tg713uxNIx9T5f2wD-Gutg+7O3-ojZwLcsTe1SFQbQ2hHDNUug3eQgDDAGGIb-bAoxtSzAIOqFQ7BnbSCLJ7QmzsdbOHYqCTu2C8wRBUKUNI9w-zT3oXnUErhJiRCLNYYhIjECYzSFQlQ1hpCcEJuEPq1heRUCJnQ4YLh86APkdmRAxDJhUOIXVUYvcuGmIljgz2uofaEKUaQ5x3NKERBoWgtBQEQAVw4IBTKIBirjTKmcW2W57YZyjioLyrAaB9ULsXJOKcMLV2MSoAAQhASEC1gghEmHVKcEdnaPSKc4ARRopypFpM4FJaSXY3RfGVOgUAVAlNCEPLJBM06jU6bIHpqVPCGJ0I4YAJNNHaPaWrUGa9CzPhsf0Dg2hsBcwMPYRgTMVDb1WcgdZ0hNmB0DlPWWNN6o3JufQjQkgPCgj6WUlQABNOI4iuYvM2E00E7C0ilCKWkV55TsCVKdg9J6zgJ4i0aTYKZ9TzCzPqqM7pvT1SlIGYHHWwyVD0L1kYSxtg0gJBESCzFsh+kgXBSM6QXSenApuM-alYQW7JyGSoG69CpTqIAAbIFIP-SYEyDCGOIfy-l8REgEA4EgGosJxUnI6QysZirJnOCUai2W8yOAooOZMI1QqRViolXsg5F8r7HNOecy5JMbmjX9nVA4LJqZAA)

### Describe the bug

can't use single table inheritance in pinia-orm.  When trying to fetch records from a sub class model it errors out reporting the following in the console log
`Cannot read properties of undefined (reading 'make')`

Adding a `.where()` before call `.all()` on the sub class model repo returns all records but does include the sub class model additional fields

**Comment by CodeDredd** [comment]
Do you really need STI then you need to follow the docs for STI or do you just need a base to extend from? Then you just need to extend without `baseEntity` -> [see here](https://pinia-orm-play.codedredd.de/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDscQLh2bxOcN3AlZcgKBAfPzXkK7cJmN9JOL-rwAJLqxAVBVJYK6eK6NJasOsCM1DizQtpSBIc29frW9EJh3YhahxDEcMGSPRujnABsk0antWwwZXsQ22ZrIDpyIPiyEFjgveCZF4hTiqIAAUzHRl8xug3UTaMa3houD+cRxTKQAOUN0ZDSS-7iD05B4CjlVjRbO+iy-qBmc2B1Hghh0AAXhwK5vLwwpJqKW4SkQYEcBBQQwfWyKNmitoTBe6GYdBHDnO0kxDo0T4vsMxGQTBn6AbOIFoRAYF0FQdHyBQNxQJwhDMC8q4IeuSGbr8qG8AAcuxrCcThlp4WeLZYnRcmcecAAsHpktx2C8fKAmTtOfpsmcV4QBQ4FwfGEwbmK268HuS4qAA8gASgAsopVr4eeamWdZGHnJSukUFwkzEjRr4bFOOwzgAuswRh0AYZpoKAACCYBgJMCzoKAqS6gYECpEQAA8VDZAAOuYKjwJIVAALw1SAAB+NRRBQMwGA10YUFpbV1SoKhgKV3CtSAMxZuqPU2Kk9TBLQkbcFmHDDfVuhTZuiA2Jto21OqU14PIrAHSoAB8I0qFV2QqFApXIMgJ1mBQkQUBg7RkmSYCbIlbXXdgN2jaNFVBCoaAwIgIRTWA2ZsNgkycW1KjEBQtQcHDCNGmYY049gyCAyDoPAMA+O5EaBwHCTFUrHQQMk2DENQzDU0QFQpAGNIyNUKj6OY+znPc6Y5gc1z0hEyAQOg6T5PiyL1O0-TjP1WDYDWJdZMK5LHmIHq1N0xriCq2DT7EEDdPVRbzyOUQdC6nU0gqOT1hGIwD2zGAAQgioBwVlWADkCyB3VDt6hwzvk3iet6n7Ad4CogdBeBodZI7kcuzuBMe1lwvO-7RiVongeTMMEIAfsad1XVM0vhTiOx4kzX+DcTfaNnlPYPYtfyPXOtNyoLcx-rrDaHnEs98D08D6Pkx5B42gYDd5OcWgKiUh7IHr4HABSrC6OYaisIggce7srClDvALKtIkSEioACi2DwGYe0cIHft1YlU91fDXdN3nhARey96qryoOvRoW9Tg713uxNIx9T5f2wD-Gutg+7O3-ojZwLcsTe1SFQbQ2hHDNUug3eQgDDAGGIb-bAoxtSzAIOqFQ7BnbSCLJ7QmzsdbOHYqCTu2C8wRBUKUNI9w-zT3oXnUErhJiRCLNYYhIjECYzSFQlQ1hpCcEJuEPq1heRUCJnQ4YLh86APkdmRAxDJhUOIXVUYvcuGmIljgz2uofaEKUaQ5x3NKERBoWgtBQEQAVw4IBTKIBirjTKmcW2W57YZyjioLyrAaB9ULsXJOKcMLV2MSoAAQhASEC1gghEmHVKcEdnaPSKc4ARRopypFpM4FJaSXY3RfGVOgUAVAlNCEPLJBM06jU6bIHpqVPCGJ0I4YAJNNHaPaWrUGa9CzPhsf0Dg2hsBcwMPYRgTMVDb1WcgdZ0hNmB0DlPWWNN6o3JufQjQkgPCgj6WUlQABNOI4iuYvM2E00E7C0ilCKWkV55TsCVKdg9J6zgJ4i0aTYKZ9TzCzPqqM7pvT1SlIGYHHWwyVD0L1kYSxtg0gJBESCzFsh+kgXBaNeh6KenApuM-alYQW7JyGSoG69CpTqIAAbIFIP-SYEyDCGOIfy-l8REgEA4EgGosJxUnI6dILp4ylVTKUai2W8yOAooOZMI1QqRViolXsg5F8r7HNOecy5JMbmjX9nVA4LJqZAA)

A damn....i see that my docs are wrong 🤔 .... as mentioned. just do it without `baseEntity`. You can also look at this [discussion](https://github.com/CodeDredd/pinia-orm/discussions/325)

**Comment by hsm22** [comment]
Yeah, actually just need a base to extend from so removing the `baseEntity` allowed me to achieve what I was after so thanks.

**Comment by bradley-varol** [comment]
I have this same error when using `baseEntity`. What I want to achieve is inheritance where the parent model has changes on the child. Setting a field on `Person` should also update `Adult`, but setting a field on `Adult` should not affect `Person`. Hoepfully this makes sense.
