### ISSUE TITLE
Using .whereIn with Sets

### ISSUE THREAD

**Issue by tintin10q** [CodeDredd/pinia-orm#524]
### Describe the feature

It would be great if you could give sets to the .whereIn method. Currently if you do this typescript gives an error and you also get back an empty list of results. It would be great if sets worked.

I also imagine that it would also be quite faster than using arrays because finding out if something is in a set O(1). But even if you already convert to a set behind the scenes it would still be faster if we could just pass a set directly because than you can skip the conversion. 

You probably already know this but you can check that something is a `Set` using the `instanceof` keyword. Like so:

```javascript

const a = new Set(["set"])
console.log("a is a set:", a instanceof Set)
```

I don't know if this feature could be implemented as a module because I don't really know what that means but I think this is just a simple change to an already existing thing.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
Sounds like a small change. I think it wouldn't make sense to make this a module. The only question i have is if i only take `Set` into account or also `Map`. Besides performance it wouldn't make such an impact. So i propably just convert the `Set` into an array.

**Comment by tintin10q** [comment]
I don't think maps really make sense. The `.whereIn` method takes a field name and then a collection with possible values. But with a map what do you take as possible value? The key or the value? Both? I don't think one of those options is more valid then the others so I don't think that Map makes sense. Maybe you see it in a different way? 

You mention converting the set to an array. Does this really not affected performance? As checking if something is in a list takes longer than with a set.

**Comment by CodeDredd** [comment]
You are right it doesn't make sense for `Map`.
Well i don't know if there is the use case there this performance difference would matter. At least with array its better for memory :). 
Besides...the code doesn't work that. Internally all wheres are collected and later executed by an `includes`. So for now i am just going to include a `Array.from` for `Set`.

**Comment by tintin10q** [comment]
Could you also add this with `whereId` as this also takes list elements. It would be great if I could also pass sets to this.

**Comment by tintin10q** [comment]
Could you add Sets as possible input to `destroy`? I often have a usecase like this:

```ts
const PlaylistRepo = useRepo(Playlist);
const playlist_ids_here = new Set(PlaylistRepo.all().map((pl) => pl.id)
const playlist_ids_came = new Set(remote_playlists.map((pl) => pl.id))
const to_delete = difference(playlist_ids_here, playlist_ids_came)

SpotifyPlaylistRepo.destroy([...to_delete])
```

It would be nice if destroy could take sets so I don't have to convert back to a list.

**Comment by CodeDredd** [comment]
@tintin10q Yeah i can add this feature to `whereId` and destroy. I wounder if not a helper is a better solution than integrating into the function.

**Comment by tintin10q** [comment]
Wel ideally you would actually iterate the sets internally right and not convert it to a list internally. Does a helper still make more sense in that case?
