### ISSUE TITLE
Make .delete know about .with

### ISSUE THREAD

**Issue by tintin10q** [CodeDredd/pinia-orm#525]
### Describe the feature

I have a reasonably big orm schema. Lets say it has humans with baskets that have a lot of bananas and kiwi and humans also have  a hat. If I want to completely delete a human and also all their baskets and bananas and their hat it would be nice if that could happen like this:

```javascript

const delete_id = 3;
const humanORM = useRepo(HumanORM);

humanORM.query()
        .whereId(delete_id)
        .with("basket", (basket) => basket.with("apples").with("kiwi"))
        .with("hats")
        .delete()
```

While this does return the entire query as you would expect with all the relationships it only deletes the top level object. The human in this case. The baskets and fruits and hats remain,

So that means that if you want to fully delete a Human you must do something like this:

```typescript
const delete_id = 3;
const humanORM = useRepo(HumanORM);

const human = humanORM.query().whereId(delete_id).with("basket", (basket) => basket.with("apples").with("kiwi")).with("hat").delete()

if (human) {
   // human with id of 3 existed
   if (human.basket) {
      
      basketORM = useRepo(basketORM)
      deleted_baskets = basketORM.query().where("human_id", delete_id).delete()
      deleted_basket_ids = deleted_baskets.map(basked => basked.id)
    
      kiwiORM = useRepo(KiwiORM)
      bananaORM = useRepo(BananaORM)

     kiwiORM.query().whereIn("basked_id", deleted_basket_ids).delete()
     bananaORM.query().whereIn("basked_id", deleted_basket_ids).delete()
   }

   if (human.hat) {
      hatORM = useRepo(HatORM)
      hatORM.destroy(human.hat.id)
   }
}
```

That is quite some code to delete everything. It would be really great if there `.delete` would just already know about the `.with` that where used. 

You might not want to change the behavior of `.delete` to not break things that depend on it behaving as it does today. You could introduce a new method that does take into account the `.with`. Here are some ideas for names: `.deleteWith`, `.burn`, `.deleteCascade`, `recursiveDelete`, `deleteRecursive`, `cascadeDelete`, `withDelete`, `withBurn().delete()` or another method on the `delete()` like `.delete.cascade()`, `.delete.withwith()`, `.delete().burn()`, `.delete().recursive()`

You could also flip it around and put the `.with` methods on the `.delete` so that would look like:

```javascript
humanORM.query().whereId(delete_id).delete().with("basket", (basket) => basket.with("apples").with("kiwi")).with("hats")
```

Let me know what you think 🙂

Another idea that I just want to throw out there is to think about defining [foreign key update and delete violations](https://en.wikipedia.org/wiki/Foreign_key#Referential_actions) on modules. That could be another way to implement this. These rules could be part of the `.belongsTo` method for instance. 

I don't really know what you mean with modules so I don't know if this can be implemented as a module. 

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
Great feature request. Makes totally sense to have this.

**Comment by tintin10q** [comment]
Excellent solution 👏
