### ISSUE TITLE
The doc website is down

### ISSUE THREAD

**Issue by tintin10q** [CodeDredd/pinia-orm#541]
### Environment

Your great doc site https://pinia-orm.codedredd.de/ sadly returns a 404 error at the moment.

### Reproduction

Go to https://pinia-orm.codedredd.de/ and see the 404.

### Describe the bug

The doc site returns a 404.

**Comment by CodeDredd** [comment]
thanks for report...saw that yesterday too....just hadnt the time to fix it yet.
