### ISSUE TITLE
Dynamic defaullt variables

### ISSUE THREAD

**Issue by tintin10q** [CodeDredd/pinia-orm#542]
### Describe the feature

It would be really great if a default value for a field in on a model could be dynamic at the runtime with a function. 

At the moment if you define a model all the default values are set when the JavaScript loads. You can set a default value at the runtime like this:

```ts
import { Model } from "pinia-orm";

const utcsec = () => Math.floor(Date.now() / 1000);

const randint = (low: number, max: number): number =>
  (Math.round(Math.random() * 10) % (max ?? low)) + (max ? low : 0);

export default class HUMAN extends Model {
  static entity = "Human"; # For a bit
  static primaryKey = "id";

  static fields() {
    return {
      id: this.uid(),
      hat_color: this.string(["red", "white", "blue"][randint(0,2)]), 
      name: this.string("Nameless"),
      last_noticed: this.number(utcsec()),
    };
  }

  declare id: string;
  declare hat_color: "red" | "white" | "blue";
  declare name: string;
  declare last_noticed: number;
}
```

Even though this takes the current time at the startup, the value of that `last_noticed` will not be updated because the value is calculated at the start.  Similarly, one `hat_color` is chosen at the start and that is it. All humans will get that hat color. It would be great if the fields could take a callable and that that callable is called to provide a return value if no value is provided for the field. 

It looks something like this:

```ts
import { Model } from "pinia-orm";

const utcsec = () => Math.floor(Date.now() / 1000);

const randint = (low: number, max: number): number =>
  (Math.round(Math.random() * 10) % (max ?? low)) + (max ? low : 0);

let count = 0;

export default class HUMAN extends Model {
  static entity = "Human";
  static primaryKey = "id";

  static fields() {
    return {
      id: this.uid(),
      hat_color: this.string((0 => ["red", "white", "blue"][randint(0,2)]), 
      name: this.string("Nameless"),
      last_noticed: this.number(utcsec),
      count: this.number(() => count++)
    };
  }

  declare id: string;
  declare hat_color: "red" | "white" | "blue";
  declare name: string;
  declare last_noticed: number;
}
```

As you can see there are already 3 different use cases for this and I think that the ability to set a default variable with a closure is really nice. 

**Attempted workaround**

I tried to update the default value by redefining the static fields method on the model instance. Like this:

```ts
HUMAN.fields = () => {
    return {
      id: Model.uid(),
      hat_color: Model.string(0 => ["red", "white", "blue"][randint(0,2)),
      name: Model.string("Nameless"),
      last_noticed: Model.number(utcsec)
    };
  };
```

But replacing the static method does not seem to work. It still returns the same time and color for me. 

I think this dynamic default variables are a good addition to pinia orm. Vuex orm [supportes](https://vuex-orm.org/guide/model/defining-models.html#generic-type) closure default values. You could also do type checking on the return type of the function. So if it is a `this.number` or `@Number` then the return type of the callable should be a number as well. Same for `this.string` then the return type of the function should be a string. `Attr` perhaps could just have `any`.

Alternatively, you could have like an `onCreate` method or something that the programmer can define on the model that can set default variables. But that would be harder to translate to the decorators I think.

Or maybe I am missing a way to do something like this?

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
Isn't this possible already with `mutators` ? But i get what you mean that it might be handier to introduce functions back to the default values....thinking about it. What do you say about using `mutators` for it ?

**Comment by tintin10q** [comment]
I wrote a reply to this but I probably forgot to send it. Thanks for adding the closures! 

I think this is better because without the closures you have to augment the setters to detect that it is the "generate default value case", So for instance you could have null as the default value and then the setter could call the default value function if it gets null. For other values you would run the normal setter stuff. So this is just extra steps, and if you set later with the default value you would actually generate another default function call which is probably not what you want. 

So I really agree! We now have all the power dynamic mutilators, casts & default values ✊
