### ISSUE TITLE
Keeping reactivity intact

### ISSUE THREAD

**Issue by Juice10** [CodeDredd/pinia-orm#659]
### Describe the feature

Keeping reactivity is incredible important to keep applications performant. However Pinia-ORM (& Vuex-ORM) generate a completely new javascript object for every single model in a collection everytime a mutation is triggered for something in that collection.

This has meant we’ve been forced to move away from Vuex-ORM for our app.

It’s great to see the progress on Pinia-ORM! Maybe this something Pinia-ORM could fix?

more info; https://github.com/vuex-orm/vuex-orm/issues/746

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
That sound like something to have.
Would be really awesome if you or other can help on this. I am not yet sure how to implement it.
First thing what poped to my mind was to use the cache system already built in. But it doesn't feel right somehow....so i try to keep thinking....

**Comment by Juice10** [comment]
Initially I was planning to just build this for Vuex-ORM 0.x since that is what we used. But looking at the code I didn’t know how to make it happen. And then looking at 1.x I was even more confused. Willingness to help is here. But know how is lacking for me as well

**Comment by CodeDredd** [comment]
@Juice10 I solved it. Took me some thinking but now the one performance bug will go away 😉

**Comment by Juice10** [comment]
Wow @CodeDredd this is incredibly cool! What a great job!

**Comment by Juice10** [comment]
Is there any way to get around the JSON comparison? `JSON.stringify(savedHydratedModel) === JSON.stringify(hydratedModel)`
Maybe even return the `savedHydratedModel` before recreating the model again (as long as there are no updates)? That would make this super super fast.

Especially if you have large models the JSON stringification can be quite painful.

**Comment by CodeDredd** [comment]
@Juice10 puhhh i try to make this better....but i already searched ways comparing hydrated opjects. i needed that to be 100% sure that i don't return a saved hydratedobject for a query where you need an update. Yes i included an "update" but since pinia-orm also uses internally queries i was uncertain what happens at runtime.

**Comment by Juice10** [comment]
Thanks @CodeDredd you're a hero. I tried naively making the changes I suggested but that does break quite a lot 
![image](https://user-images.githubusercontent.com/4106/205909116-09b8f2f8-922e-46cd-b340-65a8d1698f53.png)
