### ISSUE TITLE
@OnDelete and Attr(object) leads to undefined error

### ISSUE THREAD

**Issue by erikpols** [CodeDredd/pinia-orm#748]
### Environment

latest npm/vue3/pinia/pinia-orm

### Reproduction

Consider these classes:

class Location extends Model {}
class Country extends Model {
    @HasOne(() => Location, 'locationId') @OnDelete('cascade') declare location: Location;
}

class PartyCenter extends Model {
  @Str('Main Street 1, NL') declare location: string;
}

### Describe the bug

The OnDelete decorator seems to build a list of fields that need to be deleted, however it seems to be a global list? In any case, when using the OnDelete decorator on a field like above which also exists on another model as a different type (in the example the 'location' field), you get a TypeError:

typeError: this.schemas[this.entity][key].onDelete is not a function

### Additional context

My question would be why this function:
https://github.com/CodeDredd/pinia-orm/blob/0ebc3dbad7e634c0bc7a21401d4923268a23be77/packages/pinia-orm/src/model/Model.ts#L201

is static? Is it indeed supposed to collect these fields across all models? Why is that necessary, and would it not better to restrict this to only the instance?

### Logs

```shell
Uncaught (in promise) TypeError: this.schemas[this.entity][key].onDelete is not a function
    initializeSchema index.mjs:1443
    $initializeSchema index.mjs:1602
    $boot index.mjs:1598
    Model index.mjs:1426


  static initializeSchema() {
    this.schemas[this.entity] = {};
    const registry = {
      ...this.fields(),
      ...this.registries[this.entity]
    };
    for (const key in registry) {
      const attribute = registry[key];
      this.schemas[this.entity][key] = typeof attribute === "function" ? attribute() : attribute;
      if (this.fieldsOnDelete[key])
>>>>>        this.schemas[this.entity][key] = this.schemas[this.entity][key].onDelete(this.fieldsOnDelete[key]);
    }
  }
```

**Comment by erikpols** [comment]
at this moment im not quite sure if it is a problem on my end or not. Will close for the time being

**Comment by erikpols** [comment]
at this moment im not quite sure if it is a problem on my end or not. Will close for the time being

**Comment by erikpols** [comment]
at this moment im not quite sure if it is a problem on my end or not. Will close for the time being

**Comment by erikpols** [comment]
Im reopening this. This seems to be a real issue.

**Comment by CodeDredd** [comment]
Hi again :)
Thanks for finding this bug.

> My question would be why this function:
> [pinia-orm/packages/pinia-orm/src/model/Model.ts](https://github.com/CodeDredd/pinia-orm/blob/0ebc3dbad7e634c0bc7a21401d4923268a23be77/packages/pinia-orm/src/model/Model.ts#L201)

>
> Line 201 in [0ebc3db](https://github.com/CodeDredd/pinia-orm/commit/0ebc3dbad7e634c0bc7a21401d4923268a23be77)

>
 > static setFieldDeleteMode<M extends typeof Model>( 
> is static? Is it indeed supposed to collect these fields across all models? Why is that necessary, and would it not better to restrict this to only the instance?

It has to be static so i can use decorators. Otherwise i can't register stuff to the model.
