### ISSUE TITLE
Property 'belongsToMany' does not exist on type 'typeof  ...

### ISSUE THREAD

**Issue by tintin10q** [CodeDredd/pinia-orm#8]
Thank you for creating this package!

### Reproduction

I created a simple model but the .belongsToMany gives me the error `Property 'belongsToMany' does not exist on type 'typeof ...`

### Steps to reproduce the behavior

1. Install piniaorm 
2. Create a model (group.ts)

```js
import { Model } from "pinia-orm";

import GroupMember from "./GroupMember";
import Member from "./Member";

export default class Group extends Model {
  static entity = "Group";

  static fields() {
    return {
      id: this.uid(),
      title: this.string(""),
      description: this.string(""),
      members: this.belongsToMany(Member, GroupMember, "group_id", "member_id"),
    };
  }
}
```

3. See that your editor (Webstorm in my case) says that belongsToMany does not exist.

### Expected behavior

I would expect this.belongsToMany to exist and behave just like the original docs described it. https://vuex-orm.org/guide/model/relationships.html#many-to-many

### Actual behavior

It says belongsToMany does not exist.

### Additional information

If you didn't implement belongsToMany it might be good to put this in the README.md

**Comment by svenhue** [comment]
Hey, if you look in the sourcecode at models/relations you see that their isnt a relation called belongstoMany at this moment.

Btw the author of this repo is back at the 20.05...

What is the difference of you model Member and GroupMember? Actually is their a good workaround ?

**Comment by tintin10q** [comment]
Ok it seems  like this does not implement the docs that I linked to but the the docs from the next version. Ok.

Is there anyway way I can help? I have never looked behind the scenes so how would it work?

**Comment by svenhue** [comment]
If you explain your goal I think we will find an solution :)

As I understand you want to add a member to a group?
If yes, you need the model group and member.

Solution 1: Add an belongsto fields to the member which points to the group model
Solution 2: Add the fields hasMany to the group model and point to member

**Comment by tintin10q** [comment]
Thanks you for replying!



> Hey, if you look in the sourcecode at models/relations you see that their isnt a relation called belongstoMany at this moment.

Thanks I did look and saw that.

> Btw the author of this repo is back at the 20.05...

Thanks I now read that in the discussions aswell. 

> What is the difference of you model Member and GroupMember?

GroupMember is a table with group_id and member_id

> So you named your class Post but your entity is Group? 

Yeah that was a mistake I edited it now. 

> If you want to relate members to a group you could add a field hasMany instead of belongstoMany. With this approach you could associate a member with many groups. Also you could add a group_id to the member with the relation Belongsto.

So in my code I actually have Humans, (which I renamed member in my example) and Groups. A Human can be part of many groups and a group has many members. For this reason I can't just have a group_id forein key on the Human. Do you suggest that I have another Model, GroupMember and than Human and Group both have hasMany GroupMember? I think that would work!

I think I can indeed just replace my belongsToMany with hasMany on both Models with a thirt 'bridge' model in between. I am going to try this now. Thanks for this insigth. I will let you know how this goes for me. 

> If the author won't add this, I will do it :)

Thank you so much for that! I tried to see yesterday if I could add it but I am not at all familiar with the the code and I got stuck.

**Comment by tintin10q** [comment]
I can actually give the bridge model a belongsTo relationship! So GroupMember belongsTo Group and BelongsTo Member. I think that this actually covers everything that this.belongsToMany did in general! This is really great. I even think this is a better more explicit approach than belongsToMany but it might be slower I don't know about that.

I find this approach a more natural way of doing things and also reminds me more of how you do it with sql tables. This could be added to the docs like hey you don't actually need belongsToMany and then with an update example.

From:

```js
// ~/models/Human.ts
// The model for a Human

import { Model } from "@vuex-orm/core";

import Group from "~/models/Group";
import GroupMembership from "~/models/bridges/GroupMembership";


export default class Human extends Model {
  static entity = "Human"; 
  static primaryKey = "id";

  static fields() {
    return {
      id: this.uid(),
      image: this.string("/logo.png"),
      name: this.string("Nameless"),
      created_groups: this.hasMany(Group, "creator_id"),
      groups: this.belongsToMany(Group, GroupMembership, "group_id", "human_id"),
      is_paying_us: this.boolean(false),
    };
  }
}

// ~/models/Group.ts
//  The model for a Group

import { Model } from "@vuex-orm/core";
import Human from "~/models/Human";
import GroupMembership from "~/models/bridges/GroupMembership";

export default class Group extends Model {
  static entity = "Group";

  static fields() {
    return {
      id: this.uid(),
      name: this.string("New Group!"),
      image: this.string("/img/new_group.jpg"),
      creator_id: this.string(null),
      creator: this.belongsTo(Human, "creator_id"),
      members: this.belongsToMany(Human, GroupMembership, "group_id", "human_id"),
      moderators: this.hasMany(Human, "id"),
    };
  }
}

// ~/models/bridges/GroupMembership.ts
// Bridge table in between
import { Model } from "@vuex-orm/core";

export default class GroupMembership extends Model {
  static entity = "GroupMember";
  static primaryKey = ["group_id", "human_id"];

  static fields() {
    return {
      id: this.uid(),
      group_id: this.uid(),
      human_id: this.uid(),
    };
  }
}

```

To 

```js

// ~/models/human.ts
//  The model for a Human

import { Model } from "pinia-orm";

import Group from "~/models/Group";
import GroupMembership from "~/models/GroupMembership";

export default class Human extends Model {
  static entity = "Human";
  static primaryKey = "id";

  static fields() {
    return {
      id: this.uid(),
      image: this.string("/logo.png"),
      name: this.string("Nameless"),
      created_groups: this.hasMany(Group, "creator_id"),
      groups: this.hasMany(GroupMembership, "human_id"),
      is_paying_us: this.boolean(false),
    };
  }
}

// ~/models/Group.ts
// The model for a Group

import { Model } from "pinia-orm";
import Human from "~/models/Human";
import GroupMembership from "~/models/bridges/GroupMembership";

export default class Group extends Model {
  static entity = "Group";

  static fields() {
    return {
      id: this.uid(),
      name: this.string("New Group!"),
      image: this.string("/img/new_group.jpg"),
      creator_id: this.string(null),
      creator: this.belongsTo(Human, "creator_id"),
      members: this.hasMany(GroupMembership, "group_id"),
      };
  }
}

// ~/models/bridges/GroupMembership.ts
// Bridge table in between

import { Model } from "pinia-orm";
import Group from "~/models/Group";
import Human from "~/models/Human";

export default class GroupMembership extends Model {
  static entity = "GroupMember";
  static primaryKey = ["group_id", "human_id"];

  static fields() {
    return {
      id: this.uid(),
      group_id: this.uid(),
      human_id: this.uid(),
      group: this.belongsTo(Group, "group_id"),
      human: this.belongsTo(Human, "human_id"),
    };
  }
}



```

Looking at this it might even be a good idea to not bring back belongsToMany.

**Comment by svenhue** [comment]
Looks good!

Seems like this issue is solved? :)

**Comment by tintin10q** [comment]
Yes!

**Comment by svenhue** [comment]
@tintin10q  can you please mark your answer with the screens of the new code as the answer/ solution? :)

**Comment by tintin10q** [comment]
I don't see a button for it

**Comment by khamaileon** [comment]
Hi @tintin10q
Do you have any unit tests associated with your example? I can't get it to work. When I insert the data (for each of the 3 models), it does not create the relationships between them.

**Comment by tintin10q** [comment]
Actually now that I think of it I don't think I actually tested this at the time. I just really felt like it should work.... Which is not so good. Can you show me how you tried to insert the data? I actually paused this project to work on something else.

**Comment by khamaileon** [comment]
I finally got it to work with this:

```javascript
const human = store.$repo(Human).new();
const group = store.$repo(Group).new();
const group2 = store.$repo(Group).new();
store.$repo(GroupMembership).fresh([
    { human_id: human.id, group_id: group.id },
    { human_id: human.id, group_id: group2.id }
]);

console.log(store.$repo(Human).withAll().first());
console.log(store.$repo(GroupMembership).withAll().first());
```

The only problem is that human.groups returns a list of GroupMembership and not groups. I'll add a method in the model to handle that until the ManyToMany is implemented. By the way I am using vuex-orm next and not pinia.

**Comment by mrvanwagoner** [comment]
@khamaileon Could you please provide an example of the method in the model regarding GroupMembership vs. Groups?

**Comment by tintin10q** [comment]
> The only problem is that human.groups returns a list of GroupMembership and not groups. I'll add a method in the model to handle that until the ManyToMany is implemented. By the way I am using vuex-orm next and not pinia yet.

You can also just get the Groups with the .with on a query. But having a method is nicer.
