### ISSUE TITLE
Querying models with belongsToMany relation are extremely slow

### ISSUE THREAD

**Issue by reramjiawan** [CodeDredd/pinia-orm#823]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `ssr`, `modules`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@pinia-orm/nuxt@1.1.6`
- Build Modules:    `-`

### Reproduction

https://github.com/reramjiawan/pinia-orm-bug

### Describe the bug

Querying models with belongsToMany relation are extremely slow.

**Comment by CodeDredd** [comment]
Hmm ... lets see if i can improve it.
But is it such a problem if you use the cache?

**Comment by reramjiawan** [comment]
Hi, is it possible it can use the cache internally to speed the process up if that's how it's expected to work?

**Comment by garma83** [comment]
> Hi, is it possible it can use the cache internally to speed the process up if that's how it's expected to work?

interested in this as well. Is it necessary that the cache is exposed to users? Maybe it can work completely transparent?

**Comment by CodeDredd** [comment]
@reramjiawan @garma83 finally found some time. indeed `belongsToMany` was way to slow in queries for large numbers. Solution will be in 1.5.0 💯
