### ISSUE TITLE
Composite key for relations

### ISSUE THREAD

**Issue by reramjiawan** [CodeDredd/pinia-orm#829]
### Describe the feature

https://github.com/vuex-orm/vuex-orm/issues/295

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Check existing [discussions](https://github.com/CodeDredd/pinia-orm/discussions) and [issues](https://github.com/CodeDredd/pinia-orm/issues).

**Comment by CodeDredd** [comment]
And again a legacy feature/bug 😄 .
