### ISSUE TITLE
Simple query on large object takes very long

### ISSUE THREAD

**Issue by garma83** [CodeDredd/pinia-orm#853]
### Environment

vue3/pinia/pinia-orm/typescript

### Reproduction

create a large model (40-50 fields)
add 400 of them to the store

// the below takes about 9 seconds for me
useRepo(Model).query().get()

### Describe the bug

Querying large objects on a table with say 300-400 objects takes about 9 seconds on my computer

I didn't have this problem with Vuex ORM so that's why im registering this as a bug

### Additional context

I can use the cache but 9 seconds is just too long even as an initial query
 
Reducing the number of fields reduces the problem. (with only 2 fields, the query still takes a second or so)

From the javascript performance panel in Firefox I can see that it is the $fill function that takes up the time.

I found this reddit threat that might be related
https://www.reddit.com/r/vuejs/comments/zh5xtf/tips_for_performance_issues_while_using_pinia_orm/

Im guessing that PiniaORM creates objects after the query, which are then returned, whereas Vuex ORM returns the actual objects in the store? 
- maybe there can be some kind of lazy querying system
- maybe it would be an option to select a number of fields as part of the query?

**Comment by CodeDredd** [comment]
Well can you please provide a reproduction for it ? 🙏 
In the reddit article it also is a post from martin, where he doesn't have performance issues. So its difficult to say what the problem might be with your setup without more details.

**Comment by KIDS-interactive** [comment]
I can second this observation. I have a repo with maybe 500 (simple!) entities inside. Even a find query is taking 30ms! When I make 10 or 100 queries, it will take seconds to find the results. This is not acceptable. I have switched from upper function to lower function, now I have the problems under control. But there is clearly happening something time consuming in the query...

![Clipboard - 21  Januar 2023 14_59](https://user-images.githubusercontent.com/75635412/213993729-14d39b80-bce7-44a4-8772-216376832028.png)

**Comment by garma83** [comment]
> Well can you please provide a reproduction for it ? 🙏
> In the reddit article it also is a post from martin, where he doesn't have performance issues. So its difficult to say what the problem might be with your setup without more details.

hi!  Thanks :) so I made a reproduction, but it turned out the problem was mine :( I was fooled by the javascript profiler which pointed at pinia-orm, but it was actually the dom renderer that had a problem with putting 400 items on screen. When I did not render anything the query was around 200ms which is fine.

@KIDS-interactive  the find() query taking 30ms is curious indeed, maybe provide a reproduction recipe? Although for me it would not be a big problem ( I don't think find() queries are meant to be used in bulk)

I might not have the complete picture but it seems to me your data structure can be optimised to avoid this problem? It seems like a curious solution to use 'id_day' as the id for the store. what is Day supposed to do and would it not be better to make 'day' a field and then use a where() query to filter for day? 

I'll leave this open for @KIDS-interactive but for me this issue is done. sorry for the inconvenience.

**Comment by KIDS-interactive** [comment]
Just looking at the code of Query.js, I can see the problem... every select will hydrate every record to a model. Everytime you make a query!

https://github.com/CodeDredd/pinia-orm/blob/328c6bc83a4efe7781df02cb3b6acb253fa93dc1/packages/pinia-orm/src/query/Query.ts#L475
The all() method will be called all the time.

From an ORM viewpoint this is not the correct way, is it? First you should request the raw data, then you can hydrate the found results to models...

**Comment by KIDS-interactive** [comment]
> I might not have the complete picture but it seems to me your data structure can be optimised to avoid this problem? It seems like a curious solution to use 'id_day' as the id for the store. what is Day supposed to do and would it not be better to make 'day' a field and then use a where() query to filter for day?

I could do that to save some time. But I believe that a query on a dataset of 1000 records or so should not take this amount of time. There seems to be an architectural problem. I can cook up an example when I have time.

**Comment by KIDS-interactive** [comment]
Here is a small test case. It is a simple model. In the example the query can take between 20 and 40ms (of course related to the machine handling the js). This is a performance bottleneck.

https://pinia-orm-play.codedredd.de/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDscQLh2bxOcN3AlZcgKBAfPzXkK7cJmN9JOL-rwAJLqxAVBVJYK6eK6NJasOsCM1DizQtpSBIc29frW9EJh3YhahxDEcMGSPRujnABsk0antWwwZXsQ22ZrIDpyIPiyEFjgveCZF4hTiqIAAUzHRl8xug3UTaMa3houD+cRxTKQAOUN0ZDSS-7iD05B4CjlVjRbO+iy-qBmc2B1Hghh0AAXhwK5vLwwpJqKW4SkQYEcBBQQwfWyKNmitoTBe6GYdBHDnO0kxDo0T4vsMxGQTBn6AbOIFoRAYF0FQdHyBQNxQJwhDMC8q4IeuSGbr8qG8AAcuxrCcThlp4WeLZYnRcmcecAAsHpktx2C8fKAmTtOfpsmcV4QBQ4FwfGEwbmK268HuS4qAA8gASgAsopVr4eeamWdZGHnJSukUFwkzEjRr4bFOOwzgAuswRh0AYZpoKAACCYBgJMCzoKAqS6gYECpEQAA8VDZAAOuYKjwJIVAALw1SAAB+NRRBQMwGA10YUFpbV1SoKhgKV3CtSAMxZuqPU2Kk9TBLQkbcFmHDDfVuhTZuiA2Jto21OqU14PIrAHSoAB8I0qFV2QqFApXIMgJ1mBQkQUBg7RkmSYCbIlbXXfVo0VaUAQJOY5yPXQsAnRAMCIB5iAAI7kC+2j2IDN2jaNXnw2k1ioyg0jY7dwxg-08hAzjt2kAY1M07dQSXZ5XkqITaPSPEdAEGgKjAMAKjgUjRMvgAKjzaQHAcFUrHQDM0xVzMAgk1jsyjnPc7z-OCy+dSIxrxMSwQKjS7LzOk7LdMM7L1XEEDtvZJdzyOUQPN6hwXOC9YJgHBWVYAOQLAHdXu3UXv+DcSN6qb-t4CoAdBeBIdZLq4cqGLrBUIkRiVvHAeTMMmfZ76Kd1TNL7q7yVDIDK-Bc81KiUj9P0ANx1eX8iV3YlTQItzjNQHWUAEJSmoACiFgAOIABLpgAUgA0kUXnSW5O4AIoeQCYvpIoADqAAaACaABaEClFANBGPAuh0LsMAGHgYFgMjuTSKQxCRJsIRQWSlKNHaFpYkA4ADs94ACcCdO7YErkgbA2YyqIBVpIbAfhG7aHSmg6QDgVDNUuvzUm6UubWGQHTBuCcA7t2Bg9LuXMe45n7kUGw8AcF4Ieg8Pu2ZkCTCwaw3Q1Caa1HqNoFQxDTDsLJK3CRFUxEsJwdIugABqJRKhHDAFJjTUh5CVBKMbgwrhuRpgPCytIbQeMcGTCMF4Oo5iyq6EmBUWkswMYqAAFQcN7gqbhzDsEOExjQg4HcaHWA-hwcw2iDDSGoUE7AMDK4JGztHRIjc8TJO0MXVgASK5c0SawNQZVXCNwwADWwdChYYRFpzY2aRG4+20AHAO2Tyl62sFUo2kt2H1MaQEuqwidDiK0I3Skijbp1PlHUGudd1SKJUQEjR9U8kFOkB+MA1xdDaAWTTTifM6CMFJrIaQ6U+bwMQakFBvhtDfXsPsmhyZJLyBOTYM5yDpCoPgNoZuP0bmk2zggvmRhDA3FuTTPUZhpBDCbu0G6Bx7AxOCXk5Jkw8geG0EswpvSymwK5hBBG7TK4YMcPguqWzaHYqrpMzOFgNjsIsQ46xZYOB2MsU47OeBXEeOsNXWu7B1RwpurixAblKmG3RlyylrBqW0gCaNQVKt9b4rMeKjgVAqUbACQcah8ScX42FXgRV7DtCcSJUDUlOSVAvkqNIGp7DlmIEmGBSIGMboV1lParwHzEWID1FYjYRqqD2BlRU-VorrWS3yoYVQjc7UOr-K4igFqVmexqXVTVwTzVytVgbUWFD-UmpJS6lpSaw0m2jUg2NTqg2uvSrw1gnqs6sCRZZeV1gMaTAACSWtSJMKghSMCcUSkG1p2bqnhuIJG2p6hy2OvjYmq1KbsBpoUEcEAmTAKZRAMVcaSCiAuy3G7NOnt+YqC8lnTwsdc6ByThhMuCDNgey5tfCAOjHoQGehnBtKgpypFpM4U9NA+qkq7TDL96pghhEbgHPJyBb2jWA1AGosIDA11caS0aoTODmDQzjHZhZnyTFIJxDGILGaHOOXhnhL53kNKaSRmm9zUzYD5jg-DVHLk9LozjP5iBmN3x4aUMs6V2LaEBT2RAPyaGjTBeqSFLGeHYFIHgUo2ZtBkiDaNWJGnU0smlkAA

**Comment by CodeDredd** [comment]
> The all() method will be called all the time.
From an ORM viewpoint this is not the correct way, is it? First you should request the raw data, then you can hydrate the found results to models...

You are right. Normally the hydration should be the last thing. But right now i don't know the up and downs of it. For now i just know that it would take a huge refactoring to do it that way. This is not simple because the models are holding a lot of data behaviour which influences the output.

Thanks for the example. I first need to update the playground ^^... it's still using version 1.0.0.rc.5.

For now the one thing what i have in mind which can improve the performance more is improving the hydration cache behaviour. I'll think about it.

**Comment by KIDS-interactive** [comment]
Thanks you for the effort and for acknowledging the problem. I think one of the next milestones should be fixing the querying times and hydrating the models after the filtering. I can't make pull requests but maybe I can go through the code and can come up with a refactor idea...

**Comment by garma83** [comment]
> Thanks you for the effort and for acknowledging the problem. I think one of the next milestones should be fixing the querying times and hydrating the models after the filtering. I can't make pull requests but maybe I can go through the code and can come up with a refactor idea...

I think it's useful to have a look at the code anyway and understand why it has to be done. Maybe you can suggest solutions.

It's probably not done without reason though. I can imagine the data needs to be hydrated to assist with querying relationships for example. I would not know an easy way around this. (I'm just guessing here)

Something I've wondered in the past: Why is hydration necessary anyway? Would it not be better to store the object hydrated as a Ref which can then be used by the end-user directly? From a performance pov this would probably be fastest.

**Comment by CodeDredd** [comment]
> I think one of the next milestones should be fixing the querying times and hydrating the models after the filtering

This is not that easy....models are holding for each query the "databases" which they need to resolve relations. This wouldneed a complete rewrite. (Like @garma83 already correctly guessed :))

>Something I've wondered in the past: Why is hydration necessary anyway? Would it not be better to store the object hydrated as a Ref which can then be used by the end-user directly? From a performance pov this would probably be fastest.

From the code i know and what i just explained it is right not possible to store the hydrated object and use it becuase its changing with every different query.

The next thing to improve performance would be removing casts, mutations & meta from the model object and placing it in the hydration function, so i could use more oftener a cached hydrated object and just update it.

Or the save function could also be improved. Because there data is hydrated two times (if you ask now why, well because one time it needs to `set` the data and then return it with `get`. So this can be optimzed too.

Anyway thanks for the input. I thnk it makes sense to move this to a discussion if you guys are so eager to improve it even more 😄 

But for now #889 will make some ppl more happier :) 🚀

**Comment by CodeDredd** [comment]
@KIDS-interactive Here just for you your example with the current version : [Find Speed Test](https://pinia-orm-play.codedredd.de/#N4IgDghgxg1hDmBTAziAXAbVAOwgW0XRADcBXRAWgBNE8BLEAGhGQHtSAnKQtEU7MDHhMQNZFA50wAFzqtsRAGrkABABFadFQAoAFhAA2AMxV1sKgGIdE2KLoCUp5CogqaxRAdZgz8FaVkDOmkATxcDLwB3ZxD2FWlWFUjJaUQVAFVsOg8OZEMVZTSAGToAIw4ISRQVI1YOAtUAJhUAMhUAZhFOAyJdaWkwZDQAemH+QXgAOihWPGGyShp6YaDS4bMaAA9JvAArVABfRhx8HhAAAQXSZERh5H1rKhE2Tm4icaERMQkpWXkiADKD0QVAaiHSN38gWCdBQky6HB6vD6AyGow+Uxmc0u5Gut3ulRB5wArJMAAyTACM62wW0mKDwk32ICOJwIRBxiDxwxm1me7C4ZwxXxQPxkcgUvAAwqwIogoH9zKwTCgbthZPlCioZXgwKxkDD5BlobIUAikSAUYMRmMBEJprNhpzubzECTyVSaXSGUzDscQLh2bxOcN3AlZcgKBAfPzXkK7cJmN9JOL-rwAJLqxAVBVJYK6eK6NJasOsCM1DizQtpSBIc29frW9EJh3YhahxDEcMGSPRujnABsk0antWwwZXsQ22ZrIDpyIPiyEFjgveCZF4hTiqIAAUzHRl8xug3UTaMa3houD+cRxTGgBOUN0ZDSS-7iD05B4CjlVjRbO+iy-qBmc5xXhAFB1HM2BQYYdAAF4cCuby8MKSailuEq7u+KgAPIAEoALIqDBHB4HBiH1sijZoraEwXmB76QWRwykeRQSIeclJUuST4vpO2x7H6bJnLgMF0FQrHyBQNxQJwhDMC8q6oeu6Gbr8WG8AAchA4lPEeiInk2dH2lirG6awEnnAALB6ZJSdgMnyvJAmAbOIELkxUHIfGEwbmK268HuS54URVGWjRZ4tmZ4HMXgXGTKS1JUM+r4bFOOwzgAuswRh0AYZpoKAACCYBgJMCzoKAqS6gYECpEQAA8KXEAAOuYKjwJIVAALytSAAB+NRRBQMwGJ10YUNZ-XtSoKhgHV3B9SAMxZuqo02Kk9TBLQkbcFmHAzR1ujLZuiA2Edc21Oqy14PIrCXSoAB8s0qM12QqFAdXIMgt1mBQkQUBg7RkmSYCbFl-UvR1c2NaUAQJOY5xfXQsC3RAMCIPhiAAI7kC+2j2FDr1zXNhEY2k1h4yg0gk29wzw-08jQ6Tb2kAYLOs29QRPQRxFU-j0jxHQBBoCowDACoUHY9TL4ACoi2kBwHI1Kx0JzrONTzAIJNYKgCzTwui+LksvnUWO44LCsECoyuqzzdOq+znOqy10Ou9kT3PAFRAi3qHBC5L1gmAcFZVgA5As4ftX7dSB-4NzY3qtth3gKjh7FUHR1kupxyocusFQiRGJWafh5MwwF0XvrZ+1q0vvr8p1FQyAyvwQs9SolKg6DADc7V1-IDd2JU0Bbc4PXh8VABCUpqAAohYADiAAS6YAFIANJFIRWm4TuACK+EAnL6SKAA6gAGgAmgAWhApRQDQRjwLodC7DABh4DBYA47k0ikGIJETYIR4JkkpI0do1liQDgAOwAA57zp0HtgBuSBsDZnqogHWkhsB+E7toAqeDpAOBUD1J64s6YFSFtYZA7MO7p3Dv3GGn0h5CxHjmceRQbDwBIWQz6Dwx7ZmQJMIhvDdDMNZrUeo2gVDUNMPwskvcFGNTkTwkhyi6AAGotEqEcMAOmrNaH0JUFozuHChG5GmA8Yq0htDkxIZMIwXg6j2PqroSYFRaSzEJioAAVAI0eCphHcOIQ4ImLCDgDxYdYABHBzDGIMNIZhUTsAoIbgkIuSdEidzxNk7QVdWARPrkLTJrA1D1VcJ3DAkNbBsKlmRGWVtFb8ODtocO4din1LNtYJpNNrZpE7m0jpET2rSJ0PIrQndKSaLekMpuHAW5t3VJonRESDEdTKRU6QH4wDXF0NoDZrMJJizoIwOmshpAFTFugzBqQcG+G0CDew5yWHJg0vIG5Ng7nYOkLg+A2hu6gxeXTIuGCxZGEMDcV5rM9RmGkEMLu7RXoHHsCk6JZTsmTDyB4bQWzKmjLqagoW5FMZ9IbgQxw5D2pHNYcSxuvIqAFwsBsfhDiPHOLLBwNxjivFFzwL4gJ1hGWt3YOqNFr1SWIFwo0y2NNtDCubsyjYES5pSp1ubcldjFWLOVbSCJBxmHpJJRTGVeAtX8O0BJKl0NaUlJUC+So0gBn8O2YgSYMFIiE1evXWU7qvAAsxYgPUTiNhWqoPYVVDTzVyvlorCqhhVCdzdR6v8viKAOp2QHAZ7VDXRPteq3WFtZYMPDTamlPrulZudS05NWDU1eqjb6gqojWCBsLqwLF4ENXWEJpMAAJI61IkwqCVIwBJLKUaenFuaQQBNBgk3qHrZ69NmanU5uwHmhQRwQCFMAkVEANUFpYKIN7Lcvtc4B3FioQihdPApxLhHTOZFa4YM2P7IWz8IAmK+hAH6+cO0qCnKkWkzhb00HGrSodqMgPqmCGETu4cynIFfXNaDUAaiwgMC3XxtK5qxM4OYPDpMTmFmfJMUgElCYwq5pc65ZGREvn+e0zpNHWbvNTNgMWJDyNMceSMtjpMwWIG42-ERpQywFV0toSFPZEAgpYXNOF6pEU8ZEdgUgeBSjZm0GSKNc1UkGdzSyZWQA)
